// Generated by lungo 1.71.2897 from Lean 4.34.1 for program capdagFormal. Do not edit.

import LungoKit
import CapDAGFormalProgram
import TaggedUrnFormal

/// The Lean program capdagFormal.
let program: LungoProgram = {
    precondition(TaggedUrnFormal.Wf.lungoFingerprint == "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785", "TaggedUrn.Exec.Wf of TaggedUrnFormal has another layout than the one this program was generated for: regenerate both from the same Lean definition")
    return LungoProgram(types: capdagFormal__types())
}()

/// Calls an entry point of the program with `input`; its status and output.
func entry(_ f: @escaping (UnsafePointer<UInt8>?, Int, UnsafeMutablePointer<lungo_buffer>?) -> Int32) -> LungoCall {
    { input, count in
        var buf = lungo_buffer()
        let status = f(input, count, &buf)
        let out = buf.len > 0 ? Array(UnsafeBufferPointer(start: buf.data, count: Int(buf.len))) : []
        lungo_buffer_free(&buf)
        return (status, out)
    }
}

/// Lean's CapDAG.Exec.WfCap.
public struct WfCap {
    public let input: TaggedUrnFormal.Wf
    public let output: TaggedUrnFormal.Wf
    public let other: TaggedUrnFormal.Wf
    public let effect: Effect

    public init(input: TaggedUrnFormal.Wf, output: TaggedUrnFormal.Wf, other: TaggedUrnFormal.Wf, effect: Effect) {
        self.input = input
        self.output = output
        self.other = other
        self.effect = effect
    }
}

extension WfCap {
    /// The layout fingerprint of Lean's CapDAG.Exec.WfCap.
    public static var lungoFingerprint: String { "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830" }

    /// Describes CapDAG.Exec.WfCap for polymorphic functions.
    public static var lungoType: LungoType<WfCap> {
        LungoType<WfCap>(
            expr: Lungo.inductiveExpr(0),
            encode: { w, v in
                w.u32(0)
                try LungoExternWf.lungoType.encode(&w, v.input)
                try LungoExternWf.lungoType.encode(&w, v.output)
                try LungoExternWf.lungoType.encode(&w, v.other)
                try Effect.lungoType.encode(&w, v.effect)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Exec.WfCap") }
                return WfCap(input: try LungoExternWf.lungoType.decode(&r), output: try LungoExternWf.lungoType.decode(&r), other: try LungoExternWf.lungoType.decode(&r), effect: try Effect.lungoType.decode(&r))
            })
    }
}

/// Lean's CapDAG.Effect.
public indirect enum Effect {
    /// Lean's CapDAG.Effect.unspecified.
    case unspecified
    /// Lean's CapDAG.Effect.declared.
    case declared
    /// Lean's CapDAG.Effect.none.
    case none
    /// Lean's CapDAG.Effect.patch.
    case patch
}

extension Effect: Equatable {}

extension Effect {
    /// The layout fingerprint of Lean's CapDAG.Effect.
    public static var lungoFingerprint: String { "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477" }

    /// Describes CapDAG.Effect for polymorphic functions.
    public static var lungoType: LungoType<Effect> {
        LungoType<Effect>(
            expr: Lungo.inductiveExpr(1),
            encode: { w, v in
                switch v {
                case .unspecified:
                    w.u32(0)
                case .declared:
                    w.u32(1)
                case .none:
                    w.u32(2)
                case .patch:
                    w.u32(3)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .unspecified
                case 1: return .declared
                case 2: return .none
                case 3: return .patch
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Effect")
                }
            })
    }
}

/// Lean's TaggedUrn.Constraint.
public indirect enum Constraint {
    /// Lean's TaggedUrn.Constraint.missing.
    case missing
    /// Lean's TaggedUrn.Constraint.unconstrained.
    case unconstrained
    /// Lean's TaggedUrn.Constraint.optionalNot.
    case optionalNot(value: String)
    /// Lean's TaggedUrn.Constraint.present.
    case present
    /// Lean's TaggedUrn.Constraint.presentNot.
    case presentNot(value: String)
    /// Lean's TaggedUrn.Constraint.exact.
    case exact(value: String)
    /// Lean's TaggedUrn.Constraint.absent.
    case absent
}

extension Constraint: Equatable {}

extension Constraint {
    /// The layout fingerprint of Lean's TaggedUrn.Constraint.
    public static var lungoFingerprint: String { "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7" }

    /// Describes TaggedUrn.Constraint for polymorphic functions.
    public static var lungoType: LungoType<Constraint> {
        LungoType<Constraint>(
            expr: Lungo.inductiveExpr(2),
            encode: { w, v in
                switch v {
                case .missing:
                    w.u32(0)
                case .unconstrained:
                    w.u32(1)
                case .optionalNot(let value):
                    w.u32(2)
                    try Lungo.string.encode(&w, value)
                case .present:
                    w.u32(3)
                case .presentNot(let value):
                    w.u32(4)
                    try Lungo.string.encode(&w, value)
                case .exact(let value):
                    w.u32(5)
                    try Lungo.string.encode(&w, value)
                case .absent:
                    w.u32(6)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .missing
                case 1: return .unconstrained
                case 2: return .optionalNot(value: try Lungo.string.decode(&r))
                case 3: return .present
                case 4: return .presentNot(value: try Lungo.string.decode(&r))
                case 5: return .exact(value: try Lungo.string.decode(&r))
                case 6: return .absent
                case let c: throw LungoMalformed("constructor index \(c) of TaggedUrn.Constraint")
                }
            })
    }
}

/// Describes TaggedUrn.Exec.Wf, provided by TaggedUrnFormal.
fileprivate enum LungoExternWf {
    static var lungoType: LungoType<TaggedUrnFormal.Wf> {
        let provided = TaggedUrnFormal.Wf.lungoType
        return LungoType<TaggedUrnFormal.Wf>(
            expr: Lungo.inductiveExpr(3),
            encode: { w, v in try provided.encode(&w, v) },
            decode: { r in try provided.decode(&r) })
    }
}

/// Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func accepts(_ pattern: WfCap, _ request: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_daccepts), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, pattern)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func comparable(_ a: WfCap, _ b: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dcomparable), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, a)
            try WfCap.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func dispatch(_ candidate: WfCap, _ request: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_ddispatch), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, candidate)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool
public func effectOk(_ candidate: Effect, _ request: Effect) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_deffectOk), typeArgs: [],
        args: { w in
            try Effect.lungoType.encode(&w, candidate)
            try Effect.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func equivalent(_ a: WfCap, _ b: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dequivalent), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, a)
            try WfCap.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat
public func rankingKey(_ candidate: WfCap, _ request: WfCap) throws -> (LungoNat, LungoNat) {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_drankingKey), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, candidate)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.pair(Lungo.nat, Lungo.nat)))
}

/// Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap
public func select(_ candidates: [WfCap], _ request: WfCap) throws -> WfCap? {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dselect), typeArgs: [],
        args: { w in
            try Lungo.list(WfCap.lungoType).encode(&w, candidates)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.option(WfCap.lungoType)))
}

/// Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat
public func specificity(_ c: WfCap) throws -> LungoNat {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dspecificity), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, c)
        },
        returns: .value(Lungo.nat))
}

/// Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf
public func make(_ scheme: String, _ tags: [(String, Constraint)]) throws -> TaggedUrnFormal.Wf? {
    try program.invoke(
        entry(capdagFormal__call_l_TaggedUrn_dExec_dmake), typeArgs: [],
        args: { w in
            try Lungo.string.encode(&w, scheme)
            try Lungo.list(Lungo.pair(Lungo.string, Constraint.lungoType)).encode(&w, tags)
        },
        returns: .value(Lungo.option(LungoExternWf.lungoType)))
}
