// Generated by lungo 1.81.24 from Lean 4.34.1 for program capdagFormal. Do not edit.

import LungoKit
import CapDAGFormalProgram
import TaggedUrnFormal

/// The Lean program capdagFormal.
let program: LungoProgram = {
    precondition(TaggedUrnFormal.Wf.lungoFingerprint == "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785", "TaggedUrn.Exec.Wf of TaggedUrnFormal has another layout than the one this program was generated for: regenerate both from the same Lean definition")
    return LungoProgram(types: capdagFormal__types())
}()

/// Calls an entry point of the program with `input`; its status and output.
func entry(_ f: @escaping (UnsafePointer<UInt8>?, Int, UnsafeMutablePointer<lungo_buffer>?) -> Int32) -> LungoCall {
    { input, count in
        var buf = lungo_buffer()
        let status = f(input, count, &buf)
        let out = buf.len > 0 ? Array(UnsafeBufferPointer(start: buf.data, count: Int(buf.len))) : []
        lungo_buffer_free(&buf)
        return (status, out)
    }
}

/// Lean's CapDAG.Bifaci.Credit.Gate.
public struct Gate {
    public let available: LungoNat
    public let closed: String?

    public init(available: LungoNat, closed: String?) {
        self.available = available
        self.closed = closed
    }
}

extension Gate: Equatable {}

extension Gate {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Credit.Gate.
    public static var lungoFingerprint: String { "b10dc9a4cff1977f4f6a2c415147f497f98740255d0158fb2b3a2a99d4d1b135" }

    /// Describes CapDAG.Bifaci.Credit.Gate for polymorphic functions.
    public static var lungoType: LungoType<Gate> {
        LungoType<Gate>(
            expr: Lungo.inductiveExpr(0),
            encode: { w, v in
                w.u32(0)
                try Lungo.nat.encode(&w, v.available)
                try Lungo.option(Lungo.string).encode(&w, v.closed)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Credit.Gate") }
                return Gate(available: try Lungo.nat.decode(&r), closed: try Lungo.option(Lungo.string).decode(&r))
            })
    }
}

/// Lean's CapDAG.Bifaci.Credit.Acquire.
public indirect enum Acquire {
    /// Lean's CapDAG.Bifaci.Credit.Acquire.acquired.
    case acquired(gate: Gate)
    /// Lean's CapDAG.Bifaci.Credit.Acquire.wait.
    case wait
    /// Lean's CapDAG.Bifaci.Credit.Acquire.closed.
    case closed(reason: String)
}

extension Acquire: Equatable {}

extension Acquire {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Credit.Acquire.
    public static var lungoFingerprint: String { "0dabbf62c4dad8c3f81811acc80f5c789d25191897bb2621de51b5f94e54a4c9" }

    /// Describes CapDAG.Bifaci.Credit.Acquire for polymorphic functions.
    public static var lungoType: LungoType<Acquire> {
        LungoType<Acquire>(
            expr: Lungo.inductiveExpr(1),
            encode: { w, v in
                switch v {
                case .acquired(let gate):
                    w.u32(0)
                    try Gate.lungoType.encode(&w, gate)
                case .wait:
                    w.u32(1)
                case .closed(let reason):
                    w.u32(2)
                    try Lungo.string.encode(&w, reason)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .acquired(gate: try Gate.lungoType.decode(&r))
                case 1: return .wait
                case 2: return .closed(reason: try Lungo.string.decode(&r))
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Credit.Acquire")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Credit.Window.
public struct Window {
    public let remaining: LungoNat
    public let pending: LungoNat
    public let batch: LungoNat

    public init(remaining: LungoNat, pending: LungoNat, batch: LungoNat) {
        self.remaining = remaining
        self.pending = pending
        self.batch = batch
    }
}

extension Window: Equatable {}

extension Window {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Credit.Window.
    public static var lungoFingerprint: String { "28df89763b22214ef57dfd7f1a3c0da786ff78af9768fe453cd451870749b6fe" }

    /// Describes CapDAG.Bifaci.Credit.Window for polymorphic functions.
    public static var lungoType: LungoType<Window> {
        LungoType<Window>(
            expr: Lungo.inductiveExpr(2),
            encode: { w, v in
                w.u32(0)
                try Lungo.nat.encode(&w, v.remaining)
                try Lungo.nat.encode(&w, v.pending)
                try Lungo.nat.encode(&w, v.batch)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Credit.Window") }
                return Window(remaining: try Lungo.nat.decode(&r), pending: try Lungo.nat.decode(&r), batch: try Lungo.nat.decode(&r))
            })
    }
}

/// Lean's CapDAG.Bifaci.Credit.Arrival.
public indirect enum CreditArrival {
    /// Lean's CapDAG.Bifaci.Credit.Arrival.accepted.
    case accepted(window: Window)
    /// Lean's CapDAG.Bifaci.Credit.Arrival.violation.
    case violation
}

extension CreditArrival: Equatable {}

extension CreditArrival {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Credit.Arrival.
    public static var lungoFingerprint: String { "940f01cf50eb8b763b9f44cc84753fcdbc65fbc0f816ab279408e74208649797" }

    /// Describes CapDAG.Bifaci.Credit.Arrival for polymorphic functions.
    public static var lungoType: LungoType<CreditArrival> {
        LungoType<CreditArrival>(
            expr: Lungo.inductiveExpr(3),
            encode: { w, v in
                switch v {
                case .accepted(let window):
                    w.u32(0)
                    try Window.lungoType.encode(&w, window)
                case .violation:
                    w.u32(1)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .accepted(window: try Window.lungoType.decode(&r))
                case 1: return .violation
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Credit.Arrival")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Credit.Granted.
public struct Granted {
    public let window: Window
    public let grant: LungoNat

    public init(window: Window, grant: LungoNat) {
        self.window = window
        self.grant = grant
    }
}

extension Granted: Equatable {}

extension Granted {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Credit.Granted.
    public static var lungoFingerprint: String { "47f8d3e63e9aaf7c4b602f781afce57fc832e3d4d645c6adabd25c461abed233" }

    /// Describes CapDAG.Bifaci.Credit.Granted for polymorphic functions.
    public static var lungoType: LungoType<Granted> {
        LungoType<Granted>(
            expr: Lungo.inductiveExpr(4),
            encode: { w, v in
                w.u32(0)
                try Window.lungoType.encode(&w, v.window)
                try Lungo.nat.encode(&w, v.grant)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Credit.Granted") }
                return Granted(window: try Window.lungoType.decode(&r), grant: try Lungo.nat.decode(&r))
            })
    }
}

/// Lean's CapDAG.Bifaci.Flow.FrameType.
public indirect enum FrameType {
    /// Lean's CapDAG.Bifaci.Flow.FrameType.hello.
    case hello
    /// Lean's CapDAG.Bifaci.Flow.FrameType.req.
    case req
    /// Lean's CapDAG.Bifaci.Flow.FrameType.chunk.
    case chunk
    /// Lean's CapDAG.Bifaci.Flow.FrameType.fin.
    case fin
    /// Lean's CapDAG.Bifaci.Flow.FrameType.log.
    case log
    /// Lean's CapDAG.Bifaci.Flow.FrameType.err.
    case err
    /// Lean's CapDAG.Bifaci.Flow.FrameType.heartbeat.
    case heartbeat
    /// Lean's CapDAG.Bifaci.Flow.FrameType.streamStart.
    case streamStart
    /// Lean's CapDAG.Bifaci.Flow.FrameType.streamEnd.
    case streamEnd
    /// Lean's CapDAG.Bifaci.Flow.FrameType.relayNotify.
    case relayNotify
    /// Lean's CapDAG.Bifaci.Flow.FrameType.relayState.
    case relayState
    /// Lean's CapDAG.Bifaci.Flow.FrameType.cancel.
    case cancel
    /// Lean's CapDAG.Bifaci.Flow.FrameType.credit.
    case credit
    /// Lean's CapDAG.Bifaci.Flow.FrameType.closeStream.
    case closeStream
}

extension FrameType: Equatable {}

extension FrameType {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Flow.FrameType.
    public static var lungoFingerprint: String { "3d6742b864aeb68cf6add586acfcd1a9663a3816d718f8d8aadc3c5e3dab3e2f" }

    /// Describes CapDAG.Bifaci.Flow.FrameType for polymorphic functions.
    public static var lungoType: LungoType<FrameType> {
        LungoType<FrameType>(
            expr: Lungo.inductiveExpr(5),
            encode: { w, v in
                switch v {
                case .hello:
                    w.u32(0)
                case .req:
                    w.u32(1)
                case .chunk:
                    w.u32(2)
                case .fin:
                    w.u32(3)
                case .log:
                    w.u32(4)
                case .err:
                    w.u32(5)
                case .heartbeat:
                    w.u32(6)
                case .streamStart:
                    w.u32(7)
                case .streamEnd:
                    w.u32(8)
                case .relayNotify:
                    w.u32(9)
                case .relayState:
                    w.u32(10)
                case .cancel:
                    w.u32(11)
                case .credit:
                    w.u32(12)
                case .closeStream:
                    w.u32(13)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .hello
                case 1: return .req
                case 2: return .chunk
                case 3: return .fin
                case 4: return .log
                case 5: return .err
                case 6: return .heartbeat
                case 7: return .streamStart
                case 8: return .streamEnd
                case 9: return .relayNotify
                case 10: return .relayState
                case 11: return .cancel
                case 12: return .credit
                case 13: return .closeStream
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Flow.FrameType")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Flow.Reorder.
public struct Reorder {
    public let expected: LungoNat
    public let held: [LungoNat]

    public init(expected: LungoNat, held: [LungoNat]) {
        self.expected = expected
        self.held = held
    }
}

extension Reorder: Equatable {}

extension Reorder {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Flow.Reorder.
    public static var lungoFingerprint: String { "d1e8b655f24db5e8b2348d6d41084a5c454346eb0a81fcf11b671432e72291bf" }

    /// Describes CapDAG.Bifaci.Flow.Reorder for polymorphic functions.
    public static var lungoType: LungoType<Reorder> {
        LungoType<Reorder>(
            expr: Lungo.inductiveExpr(6),
            encode: { w, v in
                w.u32(0)
                try Lungo.nat.encode(&w, v.expected)
                try Lungo.list(Lungo.nat).encode(&w, v.held)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Flow.Reorder") }
                return Reorder(expected: try Lungo.nat.decode(&r), held: try Lungo.list(Lungo.nat).decode(&r))
            })
    }
}

/// Lean's CapDAG.Bifaci.Flow.Accepted.
public indirect enum Accepted {
    /// Lean's CapDAG.Bifaci.Flow.Accepted.deliver.
    case deliver(flow: Reorder, seqs: [LungoNat])
    /// Lean's CapDAG.Bifaci.Flow.Accepted.hold.
    case hold(flow: Reorder)
    /// Lean's CapDAG.Bifaci.Flow.Accepted.stale.
    case stale
    /// Lean's CapDAG.Bifaci.Flow.Accepted.duplicate.
    case duplicate
    /// Lean's CapDAG.Bifaci.Flow.Accepted.overflow.
    case overflow
}

extension Accepted: Equatable {}

extension Accepted {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Flow.Accepted.
    public static var lungoFingerprint: String { "a821d7a044f52a71dfd932fff60d2f3560ce5197658283853a56fb54aa96b69b" }

    /// Describes CapDAG.Bifaci.Flow.Accepted for polymorphic functions.
    public static var lungoType: LungoType<Accepted> {
        LungoType<Accepted>(
            expr: Lungo.inductiveExpr(7),
            encode: { w, v in
                switch v {
                case .deliver(let flow, let seqs):
                    w.u32(0)
                    try Reorder.lungoType.encode(&w, flow)
                    try Lungo.list(Lungo.nat).encode(&w, seqs)
                case .hold(let flow):
                    w.u32(1)
                    try Reorder.lungoType.encode(&w, flow)
                case .stale:
                    w.u32(2)
                case .duplicate:
                    w.u32(3)
                case .overflow:
                    w.u32(4)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .deliver(flow: try Reorder.lungoType.decode(&r), seqs: try Lungo.list(Lungo.nat).decode(&r))
                case 1: return .hold(flow: try Reorder.lungoType.decode(&r))
                case 2: return .stale
                case 3: return .duplicate
                case 4: return .overflow
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Flow.Accepted")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Pools.State.
public struct State {
    public let pools: [Pool]
    public let queue: [Waiter]
    public let next: LungoNat

    public init(pools: [Pool], queue: [Waiter], next: LungoNat) {
        self.pools = pools
        self.queue = queue
        self.next = next
    }
}

extension State: Equatable {}

extension State {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Pools.State.
    public static var lungoFingerprint: String { "20f7299c188d09234cda39e9cc356242e2b5bc56a09cf819d12d7f50fa24989b" }

    /// Describes CapDAG.Bifaci.Pools.State for polymorphic functions.
    public static var lungoType: LungoType<State> {
        LungoType<State>(
            expr: Lungo.inductiveExpr(8),
            encode: { w, v in
                w.u32(0)
                try Lungo.list(Pool.lungoType).encode(&w, v.pools)
                try Lungo.list(Waiter.lungoType).encode(&w, v.queue)
                try Lungo.nat.encode(&w, v.next)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Pools.State") }
                return State(pools: try Lungo.list(Pool.lungoType).decode(&r), queue: try Lungo.list(Waiter.lungoType).decode(&r), next: try Lungo.nat.decode(&r))
            })
    }
}

/// Lean's CapDAG.Bifaci.Pools.Waiter.
public struct Waiter {
    public let ticket: LungoNat
    public let chain: [String]

    public init(ticket: LungoNat, chain: [String]) {
        self.ticket = ticket
        self.chain = chain
    }
}

extension Waiter: Equatable {}

extension Waiter {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Pools.Waiter.
    public static var lungoFingerprint: String { "48d81c7e41df114e88751bb5c1f4a84c16bac3ad28d8eacba141d45f92c79da0" }

    /// Describes CapDAG.Bifaci.Pools.Waiter for polymorphic functions.
    public static var lungoType: LungoType<Waiter> {
        LungoType<Waiter>(
            expr: Lungo.inductiveExpr(9),
            encode: { w, v in
                w.u32(0)
                try Lungo.nat.encode(&w, v.ticket)
                try Lungo.list(Lungo.string).encode(&w, v.chain)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Pools.Waiter") }
                return Waiter(ticket: try Lungo.nat.decode(&r), chain: try Lungo.list(Lungo.string).decode(&r))
            })
    }
}

/// Lean's CapDAG.Bifaci.Pools.Arrival.
public indirect enum PoolsArrival {
    /// Lean's CapDAG.Bifaci.Pools.Arrival.admitted.
    case admitted(state: State)
    /// Lean's CapDAG.Bifaci.Pools.Arrival.queued.
    case queued(state: State, ticket: LungoNat, position: LungoNat)
    /// Lean's CapDAG.Bifaci.Pools.Arrival.unknownPool.
    case unknownPool(name: String)
}

extension PoolsArrival: Equatable {}

extension PoolsArrival {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Pools.Arrival.
    public static var lungoFingerprint: String { "6bee196c56c330c4ef348f4dd5a68558b2d19105592969cc64a0e7150bd22451" }

    /// Describes CapDAG.Bifaci.Pools.Arrival for polymorphic functions.
    public static var lungoType: LungoType<PoolsArrival> {
        LungoType<PoolsArrival>(
            expr: Lungo.inductiveExpr(10),
            encode: { w, v in
                switch v {
                case .admitted(let state):
                    w.u32(0)
                    try State.lungoType.encode(&w, state)
                case .queued(let state, let ticket, let position):
                    w.u32(1)
                    try State.lungoType.encode(&w, state)
                    try Lungo.nat.encode(&w, ticket)
                    try Lungo.nat.encode(&w, position)
                case .unknownPool(let name):
                    w.u32(2)
                    try Lungo.string.encode(&w, name)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .admitted(state: try State.lungoType.decode(&r))
                case 1: return .queued(state: try State.lungoType.decode(&r), ticket: try Lungo.nat.decode(&r), position: try Lungo.nat.decode(&r))
                case 2: return .unknownPool(name: try Lungo.string.decode(&r))
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Pools.Arrival")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Pools.Patience.
public indirect enum Patience {
    /// Lean's CapDAG.Bifaci.Pools.Patience.unbounded.
    case unbounded
    /// Lean's CapDAG.Bifaci.Pools.Patience.atMost.
    case atMost(remaining: LungoNat)
    /// Lean's CapDAG.Bifaci.Pools.Patience.exhausted.
    case exhausted
}

extension Patience: Equatable {}

extension Patience {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Pools.Patience.
    public static var lungoFingerprint: String { "d32e3427e590ca6002e38cface52d020c7df74603f952bf568401f7291d5648c" }

    /// Describes CapDAG.Bifaci.Pools.Patience for polymorphic functions.
    public static var lungoType: LungoType<Patience> {
        LungoType<Patience>(
            expr: Lungo.inductiveExpr(11),
            encode: { w, v in
                switch v {
                case .unbounded:
                    w.u32(0)
                case .atMost(let remaining):
                    w.u32(1)
                    try Lungo.nat.encode(&w, remaining)
                case .exhausted:
                    w.u32(2)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .unbounded
                case 1: return .atMost(remaining: try Lungo.nat.decode(&r))
                case 2: return .exhausted
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Pools.Patience")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Request.Phase.
public indirect enum Phase {
    /// Lean's CapDAG.Bifaci.Request.Phase.created.
    case created
    /// Lean's CapDAG.Bifaci.Request.Phase.streaming.
    case streaming
}

extension Phase: Equatable {}

extension Phase {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Request.Phase.
    public static var lungoFingerprint: String { "7407437b58ce033618bf82341b13aaa9661d29a5a9b0f1bf1547ea0bfcfd8374" }

    /// Describes CapDAG.Bifaci.Request.Phase for polymorphic functions.
    public static var lungoType: LungoType<Phase> {
        LungoType<Phase>(
            expr: Lungo.inductiveExpr(12),
            encode: { w, v in
                switch v {
                case .created:
                    w.u32(0)
                case .streaming:
                    w.u32(1)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .created
                case 1: return .streaming
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Request.Phase")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Request.Emitted.
public indirect enum Emitted {
    /// Lean's CapDAG.Bifaci.Request.Emitted.streamStart.
    case streamStart(stream: String)
    /// Lean's CapDAG.Bifaci.Request.Emitted.chunk.
    case chunk(stream: String, index: LungoNat)
    /// Lean's CapDAG.Bifaci.Request.Emitted.streamEnd.
    case streamEnd(stream: String, count: LungoNat?)
    /// Lean's CapDAG.Bifaci.Request.Emitted.fin.
    case fin
    /// Lean's CapDAG.Bifaci.Request.Emitted.err.
    case err
    /// Lean's CapDAG.Bifaci.Request.Emitted.other.
    case other
}

extension Emitted: Equatable {}

extension Emitted {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Request.Emitted.
    public static var lungoFingerprint: String { "97a274be14c5baecf9c50243d3651da838c5de4375366d4102cbcff85fb211c8" }

    /// Describes CapDAG.Bifaci.Request.Emitted for polymorphic functions.
    public static var lungoType: LungoType<Emitted> {
        LungoType<Emitted>(
            expr: Lungo.inductiveExpr(13),
            encode: { w, v in
                switch v {
                case .streamStart(let stream):
                    w.u32(0)
                    try Lungo.string.encode(&w, stream)
                case .chunk(let stream, let index):
                    w.u32(1)
                    try Lungo.string.encode(&w, stream)
                    try Lungo.nat.encode(&w, index)
                case .streamEnd(let stream, let count):
                    w.u32(2)
                    try Lungo.string.encode(&w, stream)
                    try Lungo.option(Lungo.nat).encode(&w, count)
                case .fin:
                    w.u32(3)
                case .err:
                    w.u32(4)
                case .other:
                    w.u32(5)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .streamStart(stream: try Lungo.string.decode(&r))
                case 1: return .chunk(stream: try Lungo.string.decode(&r), index: try Lungo.nat.decode(&r))
                case 2: return .streamEnd(stream: try Lungo.string.decode(&r), count: try Lungo.option(Lungo.nat).decode(&r))
                case 3: return .fin
                case 4: return .err
                case 5: return .other
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Request.Emitted")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Request.Violation.
public indirect enum Violation {
    /// Lean's CapDAG.Bifaci.Request.Violation.afterEnd.
    case afterEnd
    /// Lean's CapDAG.Bifaci.Request.Violation.streamRestarted.
    case streamRestarted(stream: String)
    /// Lean's CapDAG.Bifaci.Request.Violation.streamNotOpen.
    case streamNotOpen(stream: String)
    /// Lean's CapDAG.Bifaci.Request.Violation.chunkOutOfPlace.
    case chunkOutOfPlace(stream: String, expected: LungoNat, got: LungoNat)
    /// Lean's CapDAG.Bifaci.Request.Violation.chunkCountWrong.
    case chunkCountWrong(stream: String, sent: LungoNat, said: LungoNat)
    /// Lean's CapDAG.Bifaci.Request.Violation.endWithOpenStream.
    case endWithOpenStream(stream: String)
}

extension Violation: Equatable {}

extension Violation {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Request.Violation.
    public static var lungoFingerprint: String { "203fb2fc4f8ff3c79b70871b4274852e742adf97c3cc4e6631439ec66d838f09" }

    /// Describes CapDAG.Bifaci.Request.Violation for polymorphic functions.
    public static var lungoType: LungoType<Violation> {
        LungoType<Violation>(
            expr: Lungo.inductiveExpr(14),
            encode: { w, v in
                switch v {
                case .afterEnd:
                    w.u32(0)
                case .streamRestarted(let stream):
                    w.u32(1)
                    try Lungo.string.encode(&w, stream)
                case .streamNotOpen(let stream):
                    w.u32(2)
                    try Lungo.string.encode(&w, stream)
                case .chunkOutOfPlace(let stream, let expected, let got):
                    w.u32(3)
                    try Lungo.string.encode(&w, stream)
                    try Lungo.nat.encode(&w, expected)
                    try Lungo.nat.encode(&w, got)
                case .chunkCountWrong(let stream, let sent, let said):
                    w.u32(4)
                    try Lungo.string.encode(&w, stream)
                    try Lungo.nat.encode(&w, sent)
                    try Lungo.nat.encode(&w, said)
                case .endWithOpenStream(let stream):
                    w.u32(5)
                    try Lungo.string.encode(&w, stream)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .afterEnd
                case 1: return .streamRestarted(stream: try Lungo.string.decode(&r))
                case 2: return .streamNotOpen(stream: try Lungo.string.decode(&r))
                case 3: return .chunkOutOfPlace(stream: try Lungo.string.decode(&r), expected: try Lungo.nat.decode(&r), got: try Lungo.nat.decode(&r))
                case 4: return .chunkCountWrong(stream: try Lungo.string.decode(&r), sent: try Lungo.nat.decode(&r), said: try Lungo.nat.decode(&r))
                case 5: return .endWithOpenStream(stream: try Lungo.string.decode(&r))
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Request.Violation")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Request.Disposition.
public indirect enum Disposition {
    /// Lean's CapDAG.Bifaci.Request.Disposition.route.
    case route
    /// Lean's CapDAG.Bifaci.Request.Disposition.straggler.
    case straggler
    /// Lean's CapDAG.Bifaci.Request.Disposition.noRoute.
    case noRoute
}

extension Disposition: Equatable {}

extension Disposition {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Request.Disposition.
    public static var lungoFingerprint: String { "540307dfb6e509ccde4b894c69566edd1f3f9c3223b9325e97ee91b20d0fb82f" }

    /// Describes CapDAG.Bifaci.Request.Disposition for polymorphic functions.
    public static var lungoType: LungoType<Disposition> {
        LungoType<Disposition>(
            expr: Lungo.inductiveExpr(15),
            encode: { w, v in
                switch v {
                case .route:
                    w.u32(0)
                case .straggler:
                    w.u32(1)
                case .noRoute:
                    w.u32(2)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .route
                case 1: return .straggler
                case 2: return .noRoute
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Request.Disposition")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Request.Terminal.
public indirect enum Terminal {
    /// Lean's CapDAG.Bifaci.Request.Terminal.finished.
    case finished
    /// Lean's CapDAG.Bifaci.Request.Terminal.failed.
    case failed
    /// Lean's CapDAG.Bifaci.Request.Terminal.cancelled.
    case cancelled
    /// Lean's CapDAG.Bifaci.Request.Terminal.masterDied.
    case masterDied
}

extension Terminal: Equatable {}

extension Terminal {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Request.Terminal.
    public static var lungoFingerprint: String { "3597c3196cef5e4468b5449eb0da09af414bb8c3aa40d92b027089f6ae81c870" }

    /// Describes CapDAG.Bifaci.Request.Terminal for polymorphic functions.
    public static var lungoType: LungoType<Terminal> {
        LungoType<Terminal>(
            expr: Lungo.inductiveExpr(16),
            encode: { w, v in
                switch v {
                case .finished:
                    w.u32(0)
                case .failed:
                    w.u32(1)
                case .cancelled:
                    w.u32(2)
                case .masterDied:
                    w.u32(3)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .finished
                case 1: return .failed
                case 2: return .cancelled
                case 3: return .masterDied
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Request.Terminal")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Request.Write.
public indirect enum Write {
    /// Lean's CapDAG.Bifaci.Request.Write.send.
    case send(ends: Bool)
    /// Lean's CapDAG.Bifaci.Request.Write.suppress.
    case suppress
}

extension Write: Equatable {}

extension Write {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Request.Write.
    public static var lungoFingerprint: String { "9ae21282903c8131c25ca1cc527e51fd1fa5137aa77c9ef4f3d091e9415a109a" }

    /// Describes CapDAG.Bifaci.Request.Write for polymorphic functions.
    public static var lungoType: LungoType<Write> {
        LungoType<Write>(
            expr: Lungo.inductiveExpr(17),
            encode: { w, v in
                switch v {
                case .send(let ends):
                    w.u32(0)
                    try Lungo.bool.encode(&w, ends)
                case .suppress:
                    w.u32(1)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .send(ends: try Lungo.bool.decode(&r))
                case 1: return .suppress
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Request.Write")
                }
            })
    }
}

/// Lean's CapDAG.Exec.WfCap.
public struct WfCap {
    public let input: TaggedUrnFormal.Wf
    public let output: TaggedUrnFormal.Wf
    public let other: TaggedUrnFormal.Wf
    public let effect: Effect

    public init(input: TaggedUrnFormal.Wf, output: TaggedUrnFormal.Wf, other: TaggedUrnFormal.Wf, effect: Effect) {
        self.input = input
        self.output = output
        self.other = other
        self.effect = effect
    }
}

extension WfCap {
    /// The layout fingerprint of Lean's CapDAG.Exec.WfCap.
    public static var lungoFingerprint: String { "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830" }

    /// Describes CapDAG.Exec.WfCap for polymorphic functions.
    public static var lungoType: LungoType<WfCap> {
        LungoType<WfCap>(
            expr: Lungo.inductiveExpr(18),
            encode: { w, v in
                w.u32(0)
                try LungoExternWf.lungoType.encode(&w, v.input)
                try LungoExternWf.lungoType.encode(&w, v.output)
                try LungoExternWf.lungoType.encode(&w, v.other)
                try Effect.lungoType.encode(&w, v.effect)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Exec.WfCap") }
                return WfCap(input: try LungoExternWf.lungoType.decode(&r), output: try LungoExternWf.lungoType.decode(&r), other: try LungoExternWf.lungoType.decode(&r), effect: try Effect.lungoType.decode(&r))
            })
    }
}

/// Lean's CapDAG.Effect.
public indirect enum Effect {
    /// Lean's CapDAG.Effect.unspecified.
    case unspecified
    /// Lean's CapDAG.Effect.declared.
    case declared
    /// Lean's CapDAG.Effect.none.
    case none
    /// Lean's CapDAG.Effect.patch.
    case patch
}

extension Effect: Equatable {}

extension Effect {
    /// The layout fingerprint of Lean's CapDAG.Effect.
    public static var lungoFingerprint: String { "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477" }

    /// Describes CapDAG.Effect for polymorphic functions.
    public static var lungoType: LungoType<Effect> {
        LungoType<Effect>(
            expr: Lungo.inductiveExpr(19),
            encode: { w, v in
                switch v {
                case .unspecified:
                    w.u32(0)
                case .declared:
                    w.u32(1)
                case .none:
                    w.u32(2)
                case .patch:
                    w.u32(3)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .unspecified
                case 1: return .declared
                case 2: return .none
                case 3: return .patch
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Effect")
                }
            })
    }
}

/// Lean's CapDAG.Exec.WfQuery.
public struct WfQuery {
    public let input: WfAsk
    public let output: WfAsk
    public let tags: TaggedUrnFormal.Wf
    public let effect: Effect

    public init(input: WfAsk, output: WfAsk, tags: TaggedUrnFormal.Wf, effect: Effect) {
        self.input = input
        self.output = output
        self.tags = tags
        self.effect = effect
    }
}

extension WfQuery {
    /// The layout fingerprint of Lean's CapDAG.Exec.WfQuery.
    public static var lungoFingerprint: String { "e734861d70e3177f6563c4492990bb65131f0450b8dfc62071eb61b6c5f08b8e" }

    /// Describes CapDAG.Exec.WfQuery for polymorphic functions.
    public static var lungoType: LungoType<WfQuery> {
        LungoType<WfQuery>(
            expr: Lungo.inductiveExpr(20),
            encode: { w, v in
                w.u32(0)
                try WfAsk.lungoType.encode(&w, v.input)
                try WfAsk.lungoType.encode(&w, v.output)
                try LungoExternWf.lungoType.encode(&w, v.tags)
                try Effect.lungoType.encode(&w, v.effect)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Exec.WfQuery") }
                return WfQuery(input: try WfAsk.lungoType.decode(&r), output: try WfAsk.lungoType.decode(&r), tags: try LungoExternWf.lungoType.decode(&r), effect: try Effect.lungoType.decode(&r))
            })
    }
}

/// Describes TaggedUrn.Exec.Wf, provided by TaggedUrnFormal.
fileprivate enum LungoExternWf {
    static var lungoType: LungoType<TaggedUrnFormal.Wf> {
        let provided = TaggedUrnFormal.Wf.lungoType
        return LungoType<TaggedUrnFormal.Wf>(
            expr: Lungo.inductiveExpr(21),
            encode: { w, v in try provided.encode(&w, v) },
            decode: { r in try provided.decode(&r) })
    }
}

/// Lean's CapDAG.Grade.
public indirect enum Grade {
    /// Lean's CapDAG.Grade.exact.
    case exact
    /// Lean's CapDAG.Grade.guaranteed.
    case guaranteed
    /// Lean's CapDAG.Grade.possible.
    case possible
    /// Lean's CapDAG.Grade.none.
    case none
}

extension Grade: Equatable {}

extension Grade {
    /// The layout fingerprint of Lean's CapDAG.Grade.
    public static var lungoFingerprint: String { "0a2a20a14d9ecca6121343df2d8a7f2478b3e837710ed522ed385d35efdf46f2" }

    /// Describes CapDAG.Grade for polymorphic functions.
    public static var lungoType: LungoType<Grade> {
        LungoType<Grade>(
            expr: Lungo.inductiveExpr(22),
            encode: { w, v in
                switch v {
                case .exact:
                    w.u32(0)
                case .guaranteed:
                    w.u32(1)
                case .possible:
                    w.u32(2)
                case .none:
                    w.u32(3)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .exact
                case 1: return .guaranteed
                case 2: return .possible
                case 3: return .none
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Grade")
                }
            })
    }
}

/// Lean's TaggedUrn.Constraint.
public indirect enum Constraint {
    /// Lean's TaggedUrn.Constraint.missing.
    case missing
    /// Lean's TaggedUrn.Constraint.unconstrained.
    case unconstrained
    /// Lean's TaggedUrn.Constraint.optionalNot.
    case optionalNot(value: String)
    /// Lean's TaggedUrn.Constraint.present.
    case present
    /// Lean's TaggedUrn.Constraint.presentNot.
    case presentNot(value: String)
    /// Lean's TaggedUrn.Constraint.exact.
    case exact(value: String)
    /// Lean's TaggedUrn.Constraint.absent.
    case absent
}

extension Constraint: Equatable {}

extension Constraint {
    /// The layout fingerprint of Lean's TaggedUrn.Constraint.
    public static var lungoFingerprint: String { "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7" }

    /// Describes TaggedUrn.Constraint for polymorphic functions.
    public static var lungoType: LungoType<Constraint> {
        LungoType<Constraint>(
            expr: Lungo.inductiveExpr(23),
            encode: { w, v in
                switch v {
                case .missing:
                    w.u32(0)
                case .unconstrained:
                    w.u32(1)
                case .optionalNot(let value):
                    w.u32(2)
                    try Lungo.string.encode(&w, value)
                case .present:
                    w.u32(3)
                case .presentNot(let value):
                    w.u32(4)
                    try Lungo.string.encode(&w, value)
                case .exact(let value):
                    w.u32(5)
                    try Lungo.string.encode(&w, value)
                case .absent:
                    w.u32(6)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .missing
                case 1: return .unconstrained
                case 2: return .optionalNot(value: try Lungo.string.decode(&r))
                case 3: return .present
                case 4: return .presentNot(value: try Lungo.string.decode(&r))
                case 5: return .exact(value: try Lungo.string.decode(&r))
                case 6: return .absent
                case let c: throw LungoMalformed("constructor index \(c) of TaggedUrn.Constraint")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Pools.Pool.
public struct Pool {
    public let name: String
    public let capacity: LungoNat
    public let active: LungoNat

    public init(name: String, capacity: LungoNat, active: LungoNat) {
        self.name = name
        self.capacity = capacity
        self.active = active
    }
}

extension Pool: Equatable {}

extension Pool {
    /// The layout fingerprint of Lean's CapDAG.Bifaci.Pools.Pool.
    public static var lungoFingerprint: String { "60bca9d670886c7830c76779ad692b4fbb6e4e30c0ce6b3e9d5a91a9b5b7b1e6" }

    /// Describes CapDAG.Bifaci.Pools.Pool for polymorphic functions.
    public static var lungoType: LungoType<Pool> {
        LungoType<Pool>(
            expr: Lungo.inductiveExpr(24),
            encode: { w, v in
                w.u32(0)
                try Lungo.string.encode(&w, v.name)
                try Lungo.nat.encode(&w, v.capacity)
                try Lungo.nat.encode(&w, v.active)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Bifaci.Pools.Pool") }
                return Pool(name: try Lungo.string.decode(&r), capacity: try Lungo.nat.decode(&r), active: try Lungo.nat.decode(&r))
            })
    }
}

/// Lean's CapDAG.Exec.WfAsk.
public indirect enum WfAsk {
    /// Lean's CapDAG.Exec.WfAsk.unknown.
    case unknown
    /// Lean's CapDAG.Exec.WfAsk.within.
    case within(u: TaggedUrnFormal.Wf)
    /// Lean's CapDAG.Exec.WfAsk.covers.
    case covers(u: TaggedUrnFormal.Wf)
    /// Lean's CapDAG.Exec.WfAsk.same.
    case same(u: TaggedUrnFormal.Wf)
}

extension WfAsk {
    /// The layout fingerprint of Lean's CapDAG.Exec.WfAsk.
    public static var lungoFingerprint: String { "d286477c7abc4e6bc6ee2d06889372b71a5bb06605b592ebabb6ad3eaf71b952" }

    /// Describes CapDAG.Exec.WfAsk for polymorphic functions.
    public static var lungoType: LungoType<WfAsk> {
        LungoType<WfAsk>(
            expr: Lungo.inductiveExpr(25),
            encode: { w, v in
                switch v {
                case .unknown:
                    w.u32(0)
                case .within(let u):
                    w.u32(1)
                    try LungoExternWf.lungoType.encode(&w, u)
                case .covers(let u):
                    w.u32(2)
                    try LungoExternWf.lungoType.encode(&w, u)
                case .same(let u):
                    w.u32(3)
                    try LungoExternWf.lungoType.encode(&w, u)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .unknown
                case 1: return .within(u: try LungoExternWf.lungoType.decode(&r))
                case 2: return .covers(u: try LungoExternWf.lungoType.decode(&r))
                case 3: return .same(u: try LungoExternWf.lungoType.decode(&r))
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Exec.WfAsk")
                }
            })
    }
}

/// Lean's CapDAG.Bifaci.Credit.Gate.acquire : CapDAG.Bifaci.Credit.Gate → Nat → CapDAG.Bifaci.Credit.Acquire
public func acquire(_ g: Gate, _ n: LungoNat) throws -> Acquire {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dacquire), typeArgs: [],
        args: { w in
            try Gate.lungoType.encode(&w, g)
            try Lungo.nat.encode(&w, n)
        },
        returns: .value(Acquire.lungoType))
}

/// Lean's CapDAG.Bifaci.Credit.Gate.close : CapDAG.Bifaci.Credit.Gate → String → CapDAG.Bifaci.Credit.Gate
public func close(_ g: Gate, _ reason: String) throws -> Gate {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dclose), typeArgs: [],
        args: { w in
            try Gate.lungoType.encode(&w, g)
            try Lungo.string.encode(&w, reason)
        },
        returns: .value(Gate.lungoType))
}

/// Lean's CapDAG.Bifaci.Credit.Gate.grant : CapDAG.Bifaci.Credit.Gate → Nat → CapDAG.Bifaci.Credit.Gate
public func grant(_ g: Gate, _ n: LungoNat) throws -> Gate {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dgrant), typeArgs: [],
        args: { w in
            try Gate.lungoType.encode(&w, g)
            try Lungo.nat.encode(&w, n)
        },
        returns: .value(Gate.lungoType))
}

/// Lean's CapDAG.Bifaci.Credit.Gate.opened : Nat → CapDAG.Bifaci.Credit.Gate
public func gateOpened(_ window: LungoNat) throws -> Gate {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dopened), typeArgs: [],
        args: { w in
            try Lungo.nat.encode(&w, window)
        },
        returns: .value(Gate.lungoType))
}

/// Lean's CapDAG.Bifaci.Credit.Window.arrive : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Arrival
public func windowArrive(_ w_: Window) throws -> CreditArrival {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_darrive), typeArgs: [],
        args: { w in
            try Window.lungoType.encode(&w, w_)
        },
        returns: .value(CreditArrival.lungoType))
}

/// Lean's CapDAG.Bifaci.Credit.Window.consume : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted
public func `consume`(_ w_: Window) throws -> Granted {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dconsume), typeArgs: [],
        args: { w in
            try Window.lungoType.encode(&w, w_)
        },
        returns: .value(Granted.lungoType))
}

/// Lean's CapDAG.Bifaci.Credit.Window.continued : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted
public func continued(_ w_: Window) throws -> Granted {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dcontinued), typeArgs: [],
        args: { w in
            try Window.lungoType.encode(&w, w_)
        },
        returns: .value(Granted.lungoType))
}

/// Lean's CapDAG.Bifaci.Credit.Window.flush : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted
public func flush(_ w_: Window) throws -> Granted {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dflush), typeArgs: [],
        args: { w in
            try Window.lungoType.encode(&w, w_)
        },
        returns: .value(Granted.lungoType))
}

/// Lean's CapDAG.Bifaci.Credit.Window.opened : Nat → CapDAG.Bifaci.Credit.Window
public func windowOpened(_ window: LungoNat) throws -> Window {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dopened), typeArgs: [],
        args: { w in
            try Lungo.nat.encode(&w, window)
        },
        returns: .value(Window.lungoType))
}

/// Lean's CapDAG.Bifaci.Credit.grantTarget : List (Option String) → Option String → Option (Option String)
public func grantTarget(_ streams: [String?], _ named: String?) throws -> String?? {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dgrantTarget), typeArgs: [],
        args: { w in
            try Lungo.list(Lungo.option(Lungo.string)).encode(&w, streams)
            try Lungo.option(Lungo.string).encode(&w, named)
        },
        returns: .value(Lungo.option(Lungo.option(Lungo.string))))
}

/// Lean's CapDAG.Bifaci.Credit.negotiate : Nat → Nat → Option Nat
public func negotiate(_ ours: LungoNat, _ theirs: LungoNat) throws -> LungoNat? {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dCredit_dnegotiate), typeArgs: [],
        args: { w in
            try Lungo.nat.encode(&w, ours)
            try Lungo.nat.encode(&w, theirs)
        },
        returns: .value(Lungo.option(Lungo.nat)))
}

/// Lean's CapDAG.Bifaci.Flow.FrameType.code : CapDAG.Bifaci.Flow.FrameType → Nat
public func code(_ a: FrameType) throws -> LungoNat {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_dcode), typeArgs: [],
        args: { w in
            try FrameType.lungoType.encode(&w, a)
        },
        returns: .value(Lungo.nat))
}

/// Lean's CapDAG.Bifaci.Flow.FrameType.isFlow : CapDAG.Bifaci.Flow.FrameType → Bool
public func isFlow(_ a: FrameType) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_disFlow), typeArgs: [],
        args: { w in
            try FrameType.lungoType.encode(&w, a)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Bifaci.Flow.FrameType.isTerminal : CapDAG.Bifaci.Flow.FrameType → Bool
public func isTerminal(_ a: FrameType) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_disTerminal), typeArgs: [],
        args: { w in
            try FrameType.lungoType.encode(&w, a)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Bifaci.Flow.FrameType.ofCode : Nat → Option CapDAG.Bifaci.Flow.FrameType
public func ofCode(_ a: LungoNat) throws -> FrameType? {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_dofCode), typeArgs: [],
        args: { w in
            try Lungo.nat.encode(&w, a)
        },
        returns: .value(Lungo.option(FrameType.lungoType)))
}

/// Lean's CapDAG.Bifaci.Flow.Reorder.accept : CapDAG.Bifaci.Flow.Reorder → Nat → Nat → CapDAG.Bifaci.Flow.Accepted
public func accept(_ r_: Reorder, _ seq: LungoNat, _ limit: LungoNat) throws -> Accepted {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dFlow_dReorder_daccept), typeArgs: [],
        args: { w in
            try Reorder.lungoType.encode(&w, r_)
            try Lungo.nat.encode(&w, seq)
            try Lungo.nat.encode(&w, limit)
        },
        returns: .value(Accepted.lungoType))
}

/// Lean's CapDAG.Bifaci.Flow.Reorder.start : CapDAG.Bifaci.Flow.Reorder
public func start() throws -> Reorder {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dFlow_dReorder_dstart), typeArgs: [],
        args: { _ in },
        returns: .value(Reorder.lungoType))
}

/// Lean's CapDAG.Bifaci.Pools.State.admit : CapDAG.Bifaci.Pools.State → Nat → Option CapDAG.Bifaci.Pools.State
public func admit(_ s: State, _ ticket: LungoNat) throws -> State? {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dadmit), typeArgs: [],
        args: { w in
            try State.lungoType.encode(&w, s)
            try Lungo.nat.encode(&w, ticket)
        },
        returns: .value(Lungo.option(State.lungoType)))
}

/// Lean's CapDAG.Bifaci.Pools.State.admitNext : CapDAG.Bifaci.Pools.State → Option (CapDAG.Bifaci.Pools.Waiter × CapDAG.Bifaci.Pools.State)
public func admitNext(_ s: State) throws -> (Waiter, State)? {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dadmitNext), typeArgs: [],
        args: { w in
            try State.lungoType.encode(&w, s)
        },
        returns: .value(Lungo.option(Lungo.pair(Waiter.lungoType, State.lungoType))))
}

/// Lean's CapDAG.Bifaci.Pools.State.arrive : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.Arrival
public func stateArrive(_ s: State, _ chain: [String]) throws -> PoolsArrival {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_darrive), typeArgs: [],
        args: { w in
            try State.lungoType.encode(&w, s)
            try Lungo.list(Lungo.string).encode(&w, chain)
        },
        returns: .value(PoolsArrival.lungoType))
}

/// Lean's CapDAG.Bifaci.Pools.State.empty : CapDAG.Bifaci.Pools.State
public func empty() throws -> State {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dempty), typeArgs: [],
        args: { _ in },
        returns: .value(State.lungoType))
}

/// Lean's CapDAG.Bifaci.Pools.State.hasRoom : CapDAG.Bifaci.Pools.State → List String → Bool
public func hasRoom(_ s: State, _ chain: [String]) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dhasRoom), typeArgs: [],
        args: { w in
            try State.lungoType.encode(&w, s)
            try Lungo.list(Lungo.string).encode(&w, chain)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Bifaci.Pools.State.heldBack : CapDAG.Bifaci.Pools.State → String → Nat
public func heldBack(_ s: State, _ name: String) throws -> LungoNat {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dheldBack), typeArgs: [],
        args: { w in
            try State.lungoType.encode(&w, s)
            try Lungo.string.encode(&w, name)
        },
        returns: .value(Lungo.nat))
}

/// Lean's CapDAG.Bifaci.Pools.State.join : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.Arrival
public func join(_ s: State, _ chain: [String]) throws -> PoolsArrival {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_djoin), typeArgs: [],
        args: { w in
            try State.lungoType.encode(&w, s)
            try Lungo.list(Lungo.string).encode(&w, chain)
        },
        returns: .value(PoolsArrival.lungoType))
}

/// Lean's CapDAG.Bifaci.Pools.State.leave : CapDAG.Bifaci.Pools.State → Nat → CapDAG.Bifaci.Pools.State
public func leave(_ s: State, _ ticket: LungoNat) throws -> State {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dleave), typeArgs: [],
        args: { w in
            try State.lungoType.encode(&w, s)
            try Lungo.nat.encode(&w, ticket)
        },
        returns: .value(State.lungoType))
}

/// Lean's CapDAG.Bifaci.Pools.State.position : CapDAG.Bifaci.Pools.State → Nat → Nat
public func position(_ s: State, _ ticket: LungoNat) throws -> LungoNat {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dposition), typeArgs: [],
        args: { w in
            try State.lungoType.encode(&w, s)
            try Lungo.nat.encode(&w, ticket)
        },
        returns: .value(Lungo.nat))
}

/// Lean's CapDAG.Bifaci.Pools.State.release : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.State
public func release(_ s: State, _ chain: [String]) throws -> State {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_drelease), typeArgs: [],
        args: { w in
            try State.lungoType.encode(&w, s)
            try Lungo.list(Lungo.string).encode(&w, chain)
        },
        returns: .value(State.lungoType))
}

/// Lean's CapDAG.Bifaci.Pools.State.setCapacity : CapDAG.Bifaci.Pools.State → String → Nat → CapDAG.Bifaci.Pools.State
public func setCapacity(_ s: State, _ name: String, _ capacity: LungoNat) throws -> State {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dsetCapacity), typeArgs: [],
        args: { w in
            try State.lungoType.encode(&w, s)
            try Lungo.string.encode(&w, name)
            try Lungo.nat.encode(&w, capacity)
        },
        returns: .value(State.lungoType))
}

/// Lean's CapDAG.Bifaci.Pools.advertised : Bool → String → Nat → Option Nat → Nat
public func advertised(_ running: Bool, _ pool: String, _ configured: LungoNat, _ available: LungoNat?) throws -> LungoNat {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dadvertised), typeArgs: [],
        args: { w in
            try Lungo.bool.encode(&w, running)
            try Lungo.string.encode(&w, pool)
            try Lungo.nat.encode(&w, configured)
            try Lungo.option(Lungo.nat).encode(&w, available)
        },
        returns: .value(Lungo.nat))
}

/// Lean's CapDAG.Bifaci.Pools.chain : String → List (String × List String) → List String
public func chain(_ cap: String, _ shared: [(String, [String])]) throws -> [String] {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dchain), typeArgs: [],
        args: { w in
            try Lungo.string.encode(&w, cap)
            try Lungo.list(Lungo.pair(Lungo.string, Lungo.list(Lungo.string))).encode(&w, shared)
        },
        returns: .value(Lungo.list(Lungo.string)))
}

/// Lean's CapDAG.Bifaci.Pools.effective : Nat → Option Nat → Nat
public func effective(_ configured: LungoNat, _ available: LungoNat?) throws -> LungoNat {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_deffective), typeArgs: [],
        args: { w in
            try Lungo.nat.encode(&w, configured)
            try Lungo.option(Lungo.nat).encode(&w, available)
        },
        returns: .value(Lungo.nat))
}

/// Lean's CapDAG.Bifaci.Pools.patience : Option Nat → Nat → CapDAG.Bifaci.Pools.Patience
public func patience(_ unavailableFor: LungoNat?, _ grace: LungoNat) throws -> Patience {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dPools_dpatience), typeArgs: [],
        args: { w in
            try Lungo.option(Lungo.nat).encode(&w, unavailableFor)
            try Lungo.nat.encode(&w, grace)
        },
        returns: .value(Patience.lungoType))
}

/// Lean's CapDAG.Bifaci.Request.Phase.after : CapDAG.Bifaci.Request.Phase → CapDAG.Bifaci.Flow.FrameType → CapDAG.Bifaci.Request.Phase
public func after(_ p: Phase, _ frame: FrameType) throws -> Phase {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dRequest_dPhase_dafter), typeArgs: [],
        args: { w in
            try Phase.lungoType.encode(&w, p)
            try FrameType.lungoType.encode(&w, frame)
        },
        returns: .value(Phase.lungoType))
}

/// Lean's CapDAG.Bifaci.Request.check : List CapDAG.Bifaci.Request.Emitted → Option CapDAG.Bifaci.Request.Violation
public func check(_ frames: [Emitted]) throws -> Violation? {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dRequest_dcheck), typeArgs: [],
        args: { w in
            try Lungo.list(Emitted.lungoType).encode(&w, frames)
        },
        returns: .value(Lungo.option(Violation.lungoType)))
}

/// Lean's CapDAG.Bifaci.Request.dispose : Bool → Bool → CapDAG.Bifaci.Request.Disposition
public func dispose(_ live: Bool, _ endedLately: Bool) throws -> Disposition {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dRequest_ddispose), typeArgs: [],
        args: { w in
            try Lungo.bool.encode(&w, live)
            try Lungo.bool.encode(&w, endedLately)
        },
        returns: .value(Disposition.lungoType))
}

/// Lean's CapDAG.Bifaci.Request.ledger : Int → CapDAG.Bifaci.Flow.FrameType → Nat → Int
public func ledger(_ remaining: LungoInt, _ frame: FrameType, _ granted: LungoNat) throws -> LungoInt {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dRequest_dledger), typeArgs: [],
        args: { w in
            try Lungo.int.encode(&w, remaining)
            try FrameType.lungoType.encode(&w, frame)
            try Lungo.nat.encode(&w, granted)
        },
        returns: .value(Lungo.int))
}

/// Lean's CapDAG.Bifaci.Request.terminalOf : CapDAG.Bifaci.Flow.FrameType → Option CapDAG.Bifaci.Request.Terminal
public func terminalOf(_ a: FrameType) throws -> Terminal? {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dRequest_dterminalOf), typeArgs: [],
        args: { w in
            try FrameType.lungoType.encode(&w, a)
        },
        returns: .value(Lungo.option(Terminal.lungoType)))
}

/// Lean's CapDAG.Bifaci.Request.write : Bool → CapDAG.Bifaci.Flow.FrameType → CapDAG.Bifaci.Request.Write
public func write(_ over: Bool, _ frame: FrameType) throws -> Write {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dBifaci_dRequest_dwrite), typeArgs: [],
        args: { w in
            try Lungo.bool.encode(&w, over)
            try FrameType.lungoType.encode(&w, frame)
        },
        returns: .value(Write.lungoType))
}

/// Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func accepts(_ pattern: WfCap, _ cap: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_daccepts), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, pattern)
            try WfCap.lungoType.encode(&w, cap)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func comparable(_ a: WfCap, _ b: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dcomparable), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, a)
            try WfCap.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func dispatch(_ candidate: WfCap, _ request: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_ddispatch), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, candidate)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool
public func effectOk(_ candidate: Effect, _ request: Effect) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_deffectOk), typeArgs: [],
        args: { w in
            try Effect.lungoType.encode(&w, candidate)
            try Effect.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func equivalent(_ a: WfCap, _ b: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dequivalent), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, a)
            try WfCap.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.flows : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func flows(_ a: WfCap, _ b: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dflows), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, a)
            try WfCap.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.mayDispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func mayDispatch(_ candidate: WfCap, _ request: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dmayDispatch), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, candidate)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.mayFlow : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func mayFlow(_ a: WfCap, _ b: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dmayFlow), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, a)
            try WfCap.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.queryAdmits : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool
public func queryAdmits(_ q: WfQuery, _ c: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryAdmits), typeArgs: [],
        args: { w in
            try WfQuery.lungoType.encode(&w, q)
            try WfCap.lungoType.encode(&w, c)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.queryBetween : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
public func queryBetween(_ input: TaggedUrnFormal.Wf, _ output: TaggedUrnFormal.Wf, _ tags: TaggedUrnFormal.Wf) throws -> WfQuery {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryBetween), typeArgs: [],
        args: { w in
            try LungoExternWf.lungoType.encode(&w, input)
            try LungoExternWf.lungoType.encode(&w, output)
            try LungoExternWf.lungoType.encode(&w, tags)
        },
        returns: .value(WfQuery.lungoType))
}

/// Lean's CapDAG.Exec.queryConsuming : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
public func queryConsuming(_ input: TaggedUrnFormal.Wf, _ tags: TaggedUrnFormal.Wf) throws -> WfQuery {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryConsuming), typeArgs: [],
        args: { w in
            try LungoExternWf.lungoType.encode(&w, input)
            try LungoExternWf.lungoType.encode(&w, tags)
        },
        returns: .value(WfQuery.lungoType))
}

/// Lean's CapDAG.Exec.queryGrade : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → CapDAG.Grade
public func queryGrade(_ q: WfQuery, _ c: WfCap) throws -> Grade {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryGrade), typeArgs: [],
        args: { w in
            try WfQuery.lungoType.encode(&w, q)
            try WfCap.lungoType.encode(&w, c)
        },
        returns: .value(Grade.lungoType))
}

/// Lean's CapDAG.Exec.queryMayAdmit : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool
public func queryMayAdmit(_ q: WfQuery, _ c: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryMayAdmit), typeArgs: [],
        args: { w in
            try WfQuery.lungoType.encode(&w, q)
            try WfCap.lungoType.encode(&w, c)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.queryOfPattern : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery
public func queryOfPattern(_ p: WfCap) throws -> WfQuery {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryOfPattern), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, p)
        },
        returns: .value(WfQuery.lungoType))
}

/// Lean's CapDAG.Exec.queryOfRequest : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery
public func queryOfRequest(_ r_: WfCap) throws -> WfQuery {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryOfRequest), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, r_)
        },
        returns: .value(WfQuery.lungoType))
}

/// Lean's CapDAG.Exec.queryProducing : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
public func queryProducing(_ output: TaggedUrnFormal.Wf, _ tags: TaggedUrnFormal.Wf) throws -> WfQuery {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryProducing), typeArgs: [],
        args: { w in
            try LungoExternWf.lungoType.encode(&w, output)
            try LungoExternWf.lungoType.encode(&w, tags)
        },
        returns: .value(WfQuery.lungoType))
}

/// Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat
public func rankingKey(_ candidate: WfCap, _ request: WfCap) throws -> (LungoNat, LungoNat) {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_drankingKey), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, candidate)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.pair(Lungo.nat, Lungo.nat)))
}

/// Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap
public func select(_ candidates: [WfCap], _ request: WfCap) throws -> WfCap? {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dselect), typeArgs: [],
        args: { w in
            try Lungo.list(WfCap.lungoType).encode(&w, candidates)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.option(WfCap.lungoType)))
}

/// Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat
public func specificity(_ c: WfCap) throws -> LungoNat {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dspecificity), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, c)
        },
        returns: .value(Lungo.nat))
}

/// Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf
public func make(_ scheme: String, _ tags: [(String, Constraint)]) throws -> TaggedUrnFormal.Wf? {
    try program.invoke(
        entry(capdagFormal__call_l_TaggedUrn_dExec_dmake), typeArgs: [],
        args: { w in
            try Lungo.string.encode(&w, scheme)
            try Lungo.list(Lungo.pair(Lungo.string, Constraint.lungoType)).encode(&w, tags)
        },
        returns: .value(Lungo.option(LungoExternWf.lungoType)))
}
