// Generated by lungo 1.78.3254 from Lean 4.34.1 for program capdagFormal. Do not edit.

import LungoKit
import CapDAGFormalProgram
import TaggedUrnFormal

/// The Lean program capdagFormal.
let program: LungoProgram = {
    precondition(TaggedUrnFormal.Wf.lungoFingerprint == "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785", "TaggedUrn.Exec.Wf of TaggedUrnFormal has another layout than the one this program was generated for: regenerate both from the same Lean definition")
    return LungoProgram(types: capdagFormal__types())
}()

/// Calls an entry point of the program with `input`; its status and output.
func entry(_ f: @escaping (UnsafePointer<UInt8>?, Int, UnsafeMutablePointer<lungo_buffer>?) -> Int32) -> LungoCall {
    { input, count in
        var buf = lungo_buffer()
        let status = f(input, count, &buf)
        let out = buf.len > 0 ? Array(UnsafeBufferPointer(start: buf.data, count: Int(buf.len))) : []
        lungo_buffer_free(&buf)
        return (status, out)
    }
}

/// Lean's CapDAG.Exec.WfCap.
public struct WfCap {
    public let input: TaggedUrnFormal.Wf
    public let output: TaggedUrnFormal.Wf
    public let other: TaggedUrnFormal.Wf
    public let effect: Effect

    public init(input: TaggedUrnFormal.Wf, output: TaggedUrnFormal.Wf, other: TaggedUrnFormal.Wf, effect: Effect) {
        self.input = input
        self.output = output
        self.other = other
        self.effect = effect
    }
}

extension WfCap {
    /// The layout fingerprint of Lean's CapDAG.Exec.WfCap.
    public static var lungoFingerprint: String { "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830" }

    /// Describes CapDAG.Exec.WfCap for polymorphic functions.
    public static var lungoType: LungoType<WfCap> {
        LungoType<WfCap>(
            expr: Lungo.inductiveExpr(0),
            encode: { w, v in
                w.u32(0)
                try LungoExternWf.lungoType.encode(&w, v.input)
                try LungoExternWf.lungoType.encode(&w, v.output)
                try LungoExternWf.lungoType.encode(&w, v.other)
                try Effect.lungoType.encode(&w, v.effect)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Exec.WfCap") }
                return WfCap(input: try LungoExternWf.lungoType.decode(&r), output: try LungoExternWf.lungoType.decode(&r), other: try LungoExternWf.lungoType.decode(&r), effect: try Effect.lungoType.decode(&r))
            })
    }
}

/// Lean's CapDAG.Effect.
public indirect enum Effect {
    /// Lean's CapDAG.Effect.unspecified.
    case unspecified
    /// Lean's CapDAG.Effect.declared.
    case declared
    /// Lean's CapDAG.Effect.none.
    case none
    /// Lean's CapDAG.Effect.patch.
    case patch
}

extension Effect: Equatable {}

extension Effect {
    /// The layout fingerprint of Lean's CapDAG.Effect.
    public static var lungoFingerprint: String { "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477" }

    /// Describes CapDAG.Effect for polymorphic functions.
    public static var lungoType: LungoType<Effect> {
        LungoType<Effect>(
            expr: Lungo.inductiveExpr(1),
            encode: { w, v in
                switch v {
                case .unspecified:
                    w.u32(0)
                case .declared:
                    w.u32(1)
                case .none:
                    w.u32(2)
                case .patch:
                    w.u32(3)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .unspecified
                case 1: return .declared
                case 2: return .none
                case 3: return .patch
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Effect")
                }
            })
    }
}

/// Lean's CapDAG.Exec.WfQuery.
public struct WfQuery {
    public let input: WfAsk
    public let output: WfAsk
    public let tags: TaggedUrnFormal.Wf
    public let effect: Effect

    public init(input: WfAsk, output: WfAsk, tags: TaggedUrnFormal.Wf, effect: Effect) {
        self.input = input
        self.output = output
        self.tags = tags
        self.effect = effect
    }
}

extension WfQuery {
    /// The layout fingerprint of Lean's CapDAG.Exec.WfQuery.
    public static var lungoFingerprint: String { "e734861d70e3177f6563c4492990bb65131f0450b8dfc62071eb61b6c5f08b8e" }

    /// Describes CapDAG.Exec.WfQuery for polymorphic functions.
    public static var lungoType: LungoType<WfQuery> {
        LungoType<WfQuery>(
            expr: Lungo.inductiveExpr(2),
            encode: { w, v in
                w.u32(0)
                try WfAsk.lungoType.encode(&w, v.input)
                try WfAsk.lungoType.encode(&w, v.output)
                try LungoExternWf.lungoType.encode(&w, v.tags)
                try Effect.lungoType.encode(&w, v.effect)
            },
            decode: { r in
                let c = try r.u32()
                guard c == 0 else { throw LungoMalformed("constructor index \(c) of CapDAG.Exec.WfQuery") }
                return WfQuery(input: try WfAsk.lungoType.decode(&r), output: try WfAsk.lungoType.decode(&r), tags: try LungoExternWf.lungoType.decode(&r), effect: try Effect.lungoType.decode(&r))
            })
    }
}

/// Describes TaggedUrn.Exec.Wf, provided by TaggedUrnFormal.
fileprivate enum LungoExternWf {
    static var lungoType: LungoType<TaggedUrnFormal.Wf> {
        let provided = TaggedUrnFormal.Wf.lungoType
        return LungoType<TaggedUrnFormal.Wf>(
            expr: Lungo.inductiveExpr(3),
            encode: { w, v in try provided.encode(&w, v) },
            decode: { r in try provided.decode(&r) })
    }
}

/// Lean's CapDAG.Grade.
public indirect enum Grade {
    /// Lean's CapDAG.Grade.exact.
    case exact
    /// Lean's CapDAG.Grade.guaranteed.
    case guaranteed
    /// Lean's CapDAG.Grade.possible.
    case possible
    /// Lean's CapDAG.Grade.none.
    case none
}

extension Grade: Equatable {}

extension Grade {
    /// The layout fingerprint of Lean's CapDAG.Grade.
    public static var lungoFingerprint: String { "0a2a20a14d9ecca6121343df2d8a7f2478b3e837710ed522ed385d35efdf46f2" }

    /// Describes CapDAG.Grade for polymorphic functions.
    public static var lungoType: LungoType<Grade> {
        LungoType<Grade>(
            expr: Lungo.inductiveExpr(4),
            encode: { w, v in
                switch v {
                case .exact:
                    w.u32(0)
                case .guaranteed:
                    w.u32(1)
                case .possible:
                    w.u32(2)
                case .none:
                    w.u32(3)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .exact
                case 1: return .guaranteed
                case 2: return .possible
                case 3: return .none
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Grade")
                }
            })
    }
}

/// Lean's TaggedUrn.Constraint.
public indirect enum Constraint {
    /// Lean's TaggedUrn.Constraint.missing.
    case missing
    /// Lean's TaggedUrn.Constraint.unconstrained.
    case unconstrained
    /// Lean's TaggedUrn.Constraint.optionalNot.
    case optionalNot(value: String)
    /// Lean's TaggedUrn.Constraint.present.
    case present
    /// Lean's TaggedUrn.Constraint.presentNot.
    case presentNot(value: String)
    /// Lean's TaggedUrn.Constraint.exact.
    case exact(value: String)
    /// Lean's TaggedUrn.Constraint.absent.
    case absent
}

extension Constraint: Equatable {}

extension Constraint {
    /// The layout fingerprint of Lean's TaggedUrn.Constraint.
    public static var lungoFingerprint: String { "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7" }

    /// Describes TaggedUrn.Constraint for polymorphic functions.
    public static var lungoType: LungoType<Constraint> {
        LungoType<Constraint>(
            expr: Lungo.inductiveExpr(5),
            encode: { w, v in
                switch v {
                case .missing:
                    w.u32(0)
                case .unconstrained:
                    w.u32(1)
                case .optionalNot(let value):
                    w.u32(2)
                    try Lungo.string.encode(&w, value)
                case .present:
                    w.u32(3)
                case .presentNot(let value):
                    w.u32(4)
                    try Lungo.string.encode(&w, value)
                case .exact(let value):
                    w.u32(5)
                    try Lungo.string.encode(&w, value)
                case .absent:
                    w.u32(6)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .missing
                case 1: return .unconstrained
                case 2: return .optionalNot(value: try Lungo.string.decode(&r))
                case 3: return .present
                case 4: return .presentNot(value: try Lungo.string.decode(&r))
                case 5: return .exact(value: try Lungo.string.decode(&r))
                case 6: return .absent
                case let c: throw LungoMalformed("constructor index \(c) of TaggedUrn.Constraint")
                }
            })
    }
}

/// Lean's CapDAG.Exec.WfAsk.
public indirect enum WfAsk {
    /// Lean's CapDAG.Exec.WfAsk.unknown.
    case unknown
    /// Lean's CapDAG.Exec.WfAsk.within.
    case within(u: TaggedUrnFormal.Wf)
    /// Lean's CapDAG.Exec.WfAsk.covers.
    case covers(u: TaggedUrnFormal.Wf)
    /// Lean's CapDAG.Exec.WfAsk.same.
    case same(u: TaggedUrnFormal.Wf)
}

extension WfAsk {
    /// The layout fingerprint of Lean's CapDAG.Exec.WfAsk.
    public static var lungoFingerprint: String { "d286477c7abc4e6bc6ee2d06889372b71a5bb06605b592ebabb6ad3eaf71b952" }

    /// Describes CapDAG.Exec.WfAsk for polymorphic functions.
    public static var lungoType: LungoType<WfAsk> {
        LungoType<WfAsk>(
            expr: Lungo.inductiveExpr(6),
            encode: { w, v in
                switch v {
                case .unknown:
                    w.u32(0)
                case .within(let u):
                    w.u32(1)
                    try LungoExternWf.lungoType.encode(&w, u)
                case .covers(let u):
                    w.u32(2)
                    try LungoExternWf.lungoType.encode(&w, u)
                case .same(let u):
                    w.u32(3)
                    try LungoExternWf.lungoType.encode(&w, u)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .unknown
                case 1: return .within(u: try LungoExternWf.lungoType.decode(&r))
                case 2: return .covers(u: try LungoExternWf.lungoType.decode(&r))
                case 3: return .same(u: try LungoExternWf.lungoType.decode(&r))
                case let c: throw LungoMalformed("constructor index \(c) of CapDAG.Exec.WfAsk")
                }
            })
    }
}

/// Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func accepts(_ pattern: WfCap, _ cap: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_daccepts), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, pattern)
            try WfCap.lungoType.encode(&w, cap)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func comparable(_ a: WfCap, _ b: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dcomparable), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, a)
            try WfCap.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func dispatch(_ candidate: WfCap, _ request: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_ddispatch), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, candidate)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool
public func effectOk(_ candidate: Effect, _ request: Effect) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_deffectOk), typeArgs: [],
        args: { w in
            try Effect.lungoType.encode(&w, candidate)
            try Effect.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func equivalent(_ a: WfCap, _ b: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dequivalent), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, a)
            try WfCap.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.flows : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func flows(_ a: WfCap, _ b: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dflows), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, a)
            try WfCap.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.mayDispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func mayDispatch(_ candidate: WfCap, _ request: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dmayDispatch), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, candidate)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.mayFlow : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
public func mayFlow(_ a: WfCap, _ b: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dmayFlow), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, a)
            try WfCap.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.queryAdmits : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool
public func queryAdmits(_ q: WfQuery, _ c: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryAdmits), typeArgs: [],
        args: { w in
            try WfQuery.lungoType.encode(&w, q)
            try WfCap.lungoType.encode(&w, c)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.queryBetween : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
public func queryBetween(_ input: TaggedUrnFormal.Wf, _ output: TaggedUrnFormal.Wf, _ tags: TaggedUrnFormal.Wf) throws -> WfQuery {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryBetween), typeArgs: [],
        args: { w in
            try LungoExternWf.lungoType.encode(&w, input)
            try LungoExternWf.lungoType.encode(&w, output)
            try LungoExternWf.lungoType.encode(&w, tags)
        },
        returns: .value(WfQuery.lungoType))
}

/// Lean's CapDAG.Exec.queryConsuming : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
public func queryConsuming(_ input: TaggedUrnFormal.Wf, _ tags: TaggedUrnFormal.Wf) throws -> WfQuery {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryConsuming), typeArgs: [],
        args: { w in
            try LungoExternWf.lungoType.encode(&w, input)
            try LungoExternWf.lungoType.encode(&w, tags)
        },
        returns: .value(WfQuery.lungoType))
}

/// Lean's CapDAG.Exec.queryGrade : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → CapDAG.Grade
public func queryGrade(_ q: WfQuery, _ c: WfCap) throws -> Grade {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryGrade), typeArgs: [],
        args: { w in
            try WfQuery.lungoType.encode(&w, q)
            try WfCap.lungoType.encode(&w, c)
        },
        returns: .value(Grade.lungoType))
}

/// Lean's CapDAG.Exec.queryMayAdmit : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool
public func queryMayAdmit(_ q: WfQuery, _ c: WfCap) throws -> Bool {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryMayAdmit), typeArgs: [],
        args: { w in
            try WfQuery.lungoType.encode(&w, q)
            try WfCap.lungoType.encode(&w, c)
        },
        returns: .value(Lungo.bool))
}

/// Lean's CapDAG.Exec.queryOfPattern : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery
public func queryOfPattern(_ p: WfCap) throws -> WfQuery {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryOfPattern), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, p)
        },
        returns: .value(WfQuery.lungoType))
}

/// Lean's CapDAG.Exec.queryOfRequest : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery
public func queryOfRequest(_ r_: WfCap) throws -> WfQuery {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryOfRequest), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, r_)
        },
        returns: .value(WfQuery.lungoType))
}

/// Lean's CapDAG.Exec.queryProducing : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
public func queryProducing(_ output: TaggedUrnFormal.Wf, _ tags: TaggedUrnFormal.Wf) throws -> WfQuery {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dqueryProducing), typeArgs: [],
        args: { w in
            try LungoExternWf.lungoType.encode(&w, output)
            try LungoExternWf.lungoType.encode(&w, tags)
        },
        returns: .value(WfQuery.lungoType))
}

/// Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat
public func rankingKey(_ candidate: WfCap, _ request: WfCap) throws -> (LungoNat, LungoNat) {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_drankingKey), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, candidate)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.pair(Lungo.nat, Lungo.nat)))
}

/// Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap
public func select(_ candidates: [WfCap], _ request: WfCap) throws -> WfCap? {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dselect), typeArgs: [],
        args: { w in
            try Lungo.list(WfCap.lungoType).encode(&w, candidates)
            try WfCap.lungoType.encode(&w, request)
        },
        returns: .value(Lungo.option(WfCap.lungoType)))
}

/// Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat
public func specificity(_ c: WfCap) throws -> LungoNat {
    try program.invoke(
        entry(capdagFormal__call_l_CapDAG_dExec_dspecificity), typeArgs: [],
        args: { w in
            try WfCap.lungoType.encode(&w, c)
        },
        returns: .value(Lungo.nat))
}

/// Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf
public func make(_ scheme: String, _ tags: [(String, Constraint)]) throws -> TaggedUrnFormal.Wf? {
    try program.invoke(
        entry(capdagFormal__call_l_TaggedUrn_dExec_dmake), typeArgs: [],
        args: { w in
            try Lungo.string.encode(&w, scheme)
            try Lungo.list(Lungo.pair(Lungo.string, Constraint.lungoType)).encode(&w, tags)
        },
        returns: .value(Lungo.option(LungoExternWf.lungoType)))
}
