/* Generated by lungo 1.72.2908 from Lean 4.34.1 for program capdagFormal. Do not edit. */
#include "capdagFormal.h"
#include "capdagFormal_program.h"

static const uint8_t sig_0[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_1[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_2[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_3[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_4[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_5[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x17, 0x00, 0x00,
};
static const uint8_t sig_6[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x15, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x1b, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_7[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00,
};
static const uint8_t sig_8[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x10, 0x15, 0x17, 0x10, 0x1b, 0x02, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x1b, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

void capdagFormal_initialize(void) {
    capdagFormal__initialize();
}

lungo_type *capdagFormal_wf_cap_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 0, NULL, 0);
}
lungo_value *capdagFormal_wf_cap_mk(lungo_value *input, lungo_value *output, lungo_value *other, lungo_value *effect) {
    lungo_value *fields[4] = {input, output, other, effect};
    return lungo_value_ctor(0, fields, 4);
}
const lungo_value *capdagFormal_wf_cap_input(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_wf_cap_output(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}
const lungo_value *capdagFormal_wf_cap_other(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 2);
}
const lungo_value *capdagFormal_wf_cap_effect(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 3);
}

lungo_type *capdagFormal_effect_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 1, NULL, 0);
}
lungo_value *capdagFormal_effect_unspecified(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_effect_declared(void) {
    return lungo_value_ctor(1, NULL, 0);
}
lungo_value *capdagFormal_effect_none(void) {
    return lungo_value_ctor(2, NULL, 0);
}
lungo_value *capdagFormal_effect_patch(void) {
    return lungo_value_ctor(3, NULL, 0);
}

lungo_type *capdagFormal_constraint_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 2, NULL, 0);
}
lungo_value *capdagFormal_constraint_missing(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_constraint_unconstrained(void) {
    return lungo_value_ctor(1, NULL, 0);
}
lungo_value *capdagFormal_constraint_optional_not(lungo_value *value) {
    lungo_value *fields[1] = {value};
    return lungo_value_ctor(2, fields, 1);
}
const lungo_value *capdagFormal_constraint_optional_not_value(const lungo_value *v) {
    return lungo_value_ctor_field(v, 2, 0);
}
lungo_value *capdagFormal_constraint_present(void) {
    return lungo_value_ctor(3, NULL, 0);
}
lungo_value *capdagFormal_constraint_present_not(lungo_value *value) {
    lungo_value *fields[1] = {value};
    return lungo_value_ctor(4, fields, 1);
}
const lungo_value *capdagFormal_constraint_present_not_value(const lungo_value *v) {
    return lungo_value_ctor_field(v, 4, 0);
}
lungo_value *capdagFormal_constraint_exact(lungo_value *value) {
    lungo_value *fields[1] = {value};
    return lungo_value_ctor(5, fields, 1);
}
const lungo_value *capdagFormal_constraint_exact_value(const lungo_value *v) {
    return lungo_value_ctor_field(v, 5, 0);
}
lungo_value *capdagFormal_constraint_absent(void) {
    return lungo_value_ctor(6, NULL, 0);
}

lungo_type *capdagFormal_wf_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 3, NULL, 0);
}

int32_t capdagFormal_accepts(const lungo_value *pattern, const lungo_value *request, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {pattern, request};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_daccepts, sig_0, sizeof sig_0, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_comparable(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {a, b};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dcomparable, sig_1, sizeof sig_1, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_dispatch(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {candidate, request};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_ddispatch, sig_2, sizeof sig_2, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_effect_ok(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {candidate, request};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_deffectOk, sig_3, sizeof sig_3, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_equivalent(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {a, b};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dequivalent, sig_4, sizeof sig_4, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_ranking_key(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {candidate, request};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_drankingKey, sig_5, sizeof sig_5, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_select(const lungo_value *candidates, const lungo_value *request, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {candidates, request};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dselect, sig_6, sizeof sig_6, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_specificity(const lungo_value *c, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {c};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dspecificity, sig_7, sizeof sig_7, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_make(const lungo_value *scheme, const lungo_value *tags, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {scheme, tags};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_TaggedUrn_dExec_dmake, sig_8, sizeof sig_8, NULL, 0, args, 2, result, error);
}

