/* Generated by lungo 1.88.0 from Lean 4.34.1 for program capdagFormal. Do not edit. */
#include "capdagFormal.h"
#include "capdagFormal_program.h"

static const uint8_t sig_0[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_1[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x10, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_2[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_3[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00,
};
static const uint8_t sig_4[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x1b, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_5[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x1b, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_6[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x1b, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_7[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x1b, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_8[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1b, 0x02, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00,
};
static const uint8_t sig_9[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x15, 0x14, 0x10, 0x14, 0x10, 0x00, 0x14, 0x14,
    0x10,
};
static const uint8_t sig_10[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x00,
};
static const uint8_t sig_11[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00,
};
static const uint8_t sig_12[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x02,
};
static const uint8_t sig_13[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x02,
};
static const uint8_t sig_14[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x1b, 0x05, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_15[] = {
    0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x1b, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x1b, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_16[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1b, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00,
};
static const uint8_t sig_17[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x14, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_18[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x14, 0x17, 0x1b, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_19[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x15, 0x10, 0x00, 0x1b, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_20[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00,
};
static const uint8_t sig_21[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x15, 0x10, 0x00, 0x02,
};
static const uint8_t sig_22[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x10, 0x00, 0x00,
};
static const uint8_t sig_23[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x15, 0x10, 0x00, 0x1b, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_24[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_25[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_26[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x15, 0x10, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_27[] = {
    0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x10, 0x00, 0x00, 0x1b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_28[] = {
    0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0x10, 0x00, 0x14, 0x00, 0x00, 0x00,
};
static const uint8_t sig_29[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x10, 0x15, 0x17, 0x10, 0x15, 0x10, 0x00, 0x15,
    0x10,
};
static const uint8_t sig_30[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00,
};
static const uint8_t sig_31[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00, 0x1b, 0x0b, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_32[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x0c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1b, 0x0c, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_33[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x15, 0x1b, 0x0d, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x14, 0x1b, 0x0e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_34[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x02, 0x02, 0x00, 0x1b, 0x0f, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_35[] = {
    0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x1b, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x01,
};
static const uint8_t sig_36[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x14, 0x1b, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_37[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x02, 0x1b, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x1b, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_38[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_39[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_40[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_41[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_42[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_43[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_44[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_45[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_46[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_47[] = {
    0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x1b, 0x15, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x15, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1b, 0x15, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x1b, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_48[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x15, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x15, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1b, 0x14, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_49[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1b, 0x16, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_50[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_51[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x1b, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_52[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x1b, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_53[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x15, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x15, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1b, 0x14, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_54[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x17, 0x00, 0x00,
};
static const uint8_t sig_55[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x15, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x1b, 0x12, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_56[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00,
};
static const uint8_t sig_57[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x10, 0x15, 0x17, 0x10, 0x1b, 0x17, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x1b, 0x15, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

void capdagFormal_initialize(void) {
    capdagFormal__initialize();
}

lungo_type *capdagFormal_gate_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 0, NULL, 0);
}
lungo_value *capdagFormal_gate_mk(lungo_value *available, lungo_value *closed) {
    lungo_value *fields[2] = {available, closed};
    return lungo_value_ctor(0, fields, 2);
}
const lungo_value *capdagFormal_gate_available(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_gate_closed(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}

lungo_type *capdagFormal_acquire_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 1, NULL, 0);
}
lungo_value *capdagFormal_acquire_acquired(lungo_value *gate) {
    lungo_value *fields[1] = {gate};
    return lungo_value_ctor(0, fields, 1);
}
const lungo_value *capdagFormal_acquire_acquired_gate(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
lungo_value *capdagFormal_acquire_wait(void) {
    return lungo_value_ctor(1, NULL, 0);
}
lungo_value *capdagFormal_acquire_closed(lungo_value *reason) {
    lungo_value *fields[1] = {reason};
    return lungo_value_ctor(2, fields, 1);
}
const lungo_value *capdagFormal_acquire_closed_reason(const lungo_value *v) {
    return lungo_value_ctor_field(v, 2, 0);
}

lungo_type *capdagFormal_window_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 2, NULL, 0);
}
lungo_value *capdagFormal_window_mk(lungo_value *remaining, lungo_value *pending, lungo_value *batch) {
    lungo_value *fields[3] = {remaining, pending, batch};
    return lungo_value_ctor(0, fields, 3);
}
const lungo_value *capdagFormal_window_remaining(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_window_pending(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}
const lungo_value *capdagFormal_window_batch(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 2);
}

lungo_type *capdagFormal_credit_arrival_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 3, NULL, 0);
}
lungo_value *capdagFormal_credit_arrival_accepted(lungo_value *window) {
    lungo_value *fields[1] = {window};
    return lungo_value_ctor(0, fields, 1);
}
const lungo_value *capdagFormal_credit_arrival_accepted_window(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
lungo_value *capdagFormal_credit_arrival_violation(void) {
    return lungo_value_ctor(1, NULL, 0);
}

lungo_type *capdagFormal_granted_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 4, NULL, 0);
}
lungo_value *capdagFormal_granted_mk(lungo_value *window, lungo_value *grant) {
    lungo_value *fields[2] = {window, grant};
    return lungo_value_ctor(0, fields, 2);
}
const lungo_value *capdagFormal_granted_window(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_granted_grant(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}

lungo_type *capdagFormal_frame_type_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 5, NULL, 0);
}
lungo_value *capdagFormal_frame_type_hello(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_frame_type_req(void) {
    return lungo_value_ctor(1, NULL, 0);
}
lungo_value *capdagFormal_frame_type_chunk(void) {
    return lungo_value_ctor(2, NULL, 0);
}
lungo_value *capdagFormal_frame_type_fin(void) {
    return lungo_value_ctor(3, NULL, 0);
}
lungo_value *capdagFormal_frame_type_log(void) {
    return lungo_value_ctor(4, NULL, 0);
}
lungo_value *capdagFormal_frame_type_err(void) {
    return lungo_value_ctor(5, NULL, 0);
}
lungo_value *capdagFormal_frame_type_heartbeat(void) {
    return lungo_value_ctor(6, NULL, 0);
}
lungo_value *capdagFormal_frame_type_stream_start(void) {
    return lungo_value_ctor(7, NULL, 0);
}
lungo_value *capdagFormal_frame_type_stream_end(void) {
    return lungo_value_ctor(8, NULL, 0);
}
lungo_value *capdagFormal_frame_type_relay_notify(void) {
    return lungo_value_ctor(9, NULL, 0);
}
lungo_value *capdagFormal_frame_type_relay_state(void) {
    return lungo_value_ctor(10, NULL, 0);
}
lungo_value *capdagFormal_frame_type_cancel(void) {
    return lungo_value_ctor(11, NULL, 0);
}
lungo_value *capdagFormal_frame_type_credit(void) {
    return lungo_value_ctor(12, NULL, 0);
}
lungo_value *capdagFormal_frame_type_close_stream(void) {
    return lungo_value_ctor(13, NULL, 0);
}

lungo_type *capdagFormal_reorder_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 6, NULL, 0);
}
lungo_value *capdagFormal_reorder_mk(lungo_value *expected, lungo_value *held) {
    lungo_value *fields[2] = {expected, held};
    return lungo_value_ctor(0, fields, 2);
}
const lungo_value *capdagFormal_reorder_expected(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_reorder_held(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}

lungo_type *capdagFormal_accepted_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 7, NULL, 0);
}
lungo_value *capdagFormal_accepted_deliver(lungo_value *flow, lungo_value *seqs) {
    lungo_value *fields[2] = {flow, seqs};
    return lungo_value_ctor(0, fields, 2);
}
const lungo_value *capdagFormal_accepted_deliver_flow(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_accepted_deliver_seqs(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}
lungo_value *capdagFormal_accepted_hold(lungo_value *flow) {
    lungo_value *fields[1] = {flow};
    return lungo_value_ctor(1, fields, 1);
}
const lungo_value *capdagFormal_accepted_hold_flow(const lungo_value *v) {
    return lungo_value_ctor_field(v, 1, 0);
}
lungo_value *capdagFormal_accepted_stale(void) {
    return lungo_value_ctor(2, NULL, 0);
}
lungo_value *capdagFormal_accepted_duplicate(void) {
    return lungo_value_ctor(3, NULL, 0);
}
lungo_value *capdagFormal_accepted_overflow(void) {
    return lungo_value_ctor(4, NULL, 0);
}

lungo_type *capdagFormal_state_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 8, NULL, 0);
}
lungo_value *capdagFormal_state_mk(lungo_value *pools, lungo_value *queue, lungo_value *next) {
    lungo_value *fields[3] = {pools, queue, next};
    return lungo_value_ctor(0, fields, 3);
}
const lungo_value *capdagFormal_state_pools(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_state_queue(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}
const lungo_value *capdagFormal_state_next(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 2);
}

lungo_type *capdagFormal_waiter_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 9, NULL, 0);
}
lungo_value *capdagFormal_waiter_mk(lungo_value *ticket, lungo_value *chain) {
    lungo_value *fields[2] = {ticket, chain};
    return lungo_value_ctor(0, fields, 2);
}
const lungo_value *capdagFormal_waiter_ticket(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_waiter_chain(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}

lungo_type *capdagFormal_pools_arrival_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 10, NULL, 0);
}
lungo_value *capdagFormal_pools_arrival_admitted(lungo_value *state) {
    lungo_value *fields[1] = {state};
    return lungo_value_ctor(0, fields, 1);
}
const lungo_value *capdagFormal_pools_arrival_admitted_state(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
lungo_value *capdagFormal_pools_arrival_queued(lungo_value *state, lungo_value *ticket, lungo_value *position) {
    lungo_value *fields[3] = {state, ticket, position};
    return lungo_value_ctor(1, fields, 3);
}
const lungo_value *capdagFormal_pools_arrival_queued_state(const lungo_value *v) {
    return lungo_value_ctor_field(v, 1, 0);
}
const lungo_value *capdagFormal_pools_arrival_queued_ticket(const lungo_value *v) {
    return lungo_value_ctor_field(v, 1, 1);
}
const lungo_value *capdagFormal_pools_arrival_queued_position(const lungo_value *v) {
    return lungo_value_ctor_field(v, 1, 2);
}
lungo_value *capdagFormal_pools_arrival_unknown_pool(lungo_value *name) {
    lungo_value *fields[1] = {name};
    return lungo_value_ctor(2, fields, 1);
}
const lungo_value *capdagFormal_pools_arrival_unknown_pool_name(const lungo_value *v) {
    return lungo_value_ctor_field(v, 2, 0);
}

lungo_type *capdagFormal_patience_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 11, NULL, 0);
}
lungo_value *capdagFormal_patience_unbounded(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_patience_at_most(lungo_value *remaining) {
    lungo_value *fields[1] = {remaining};
    return lungo_value_ctor(1, fields, 1);
}
const lungo_value *capdagFormal_patience_at_most_remaining(const lungo_value *v) {
    return lungo_value_ctor_field(v, 1, 0);
}
lungo_value *capdagFormal_patience_exhausted(void) {
    return lungo_value_ctor(2, NULL, 0);
}

lungo_type *capdagFormal_phase_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 12, NULL, 0);
}
lungo_value *capdagFormal_phase_created(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_phase_streaming(void) {
    return lungo_value_ctor(1, NULL, 0);
}

lungo_type *capdagFormal_emitted_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 13, NULL, 0);
}
lungo_value *capdagFormal_emitted_stream_start(lungo_value *stream) {
    lungo_value *fields[1] = {stream};
    return lungo_value_ctor(0, fields, 1);
}
const lungo_value *capdagFormal_emitted_stream_start_stream(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
lungo_value *capdagFormal_emitted_chunk(lungo_value *stream, lungo_value *index) {
    lungo_value *fields[2] = {stream, index};
    return lungo_value_ctor(1, fields, 2);
}
const lungo_value *capdagFormal_emitted_chunk_stream(const lungo_value *v) {
    return lungo_value_ctor_field(v, 1, 0);
}
const lungo_value *capdagFormal_emitted_chunk_index(const lungo_value *v) {
    return lungo_value_ctor_field(v, 1, 1);
}
lungo_value *capdagFormal_emitted_stream_end(lungo_value *stream, lungo_value *count) {
    lungo_value *fields[2] = {stream, count};
    return lungo_value_ctor(2, fields, 2);
}
const lungo_value *capdagFormal_emitted_stream_end_stream(const lungo_value *v) {
    return lungo_value_ctor_field(v, 2, 0);
}
const lungo_value *capdagFormal_emitted_stream_end_count(const lungo_value *v) {
    return lungo_value_ctor_field(v, 2, 1);
}
lungo_value *capdagFormal_emitted_fin(void) {
    return lungo_value_ctor(3, NULL, 0);
}
lungo_value *capdagFormal_emitted_err(void) {
    return lungo_value_ctor(4, NULL, 0);
}
lungo_value *capdagFormal_emitted_other(void) {
    return lungo_value_ctor(5, NULL, 0);
}

lungo_type *capdagFormal_violation_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 14, NULL, 0);
}
lungo_value *capdagFormal_violation_after_end(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_violation_stream_restarted(lungo_value *stream) {
    lungo_value *fields[1] = {stream};
    return lungo_value_ctor(1, fields, 1);
}
const lungo_value *capdagFormal_violation_stream_restarted_stream(const lungo_value *v) {
    return lungo_value_ctor_field(v, 1, 0);
}
lungo_value *capdagFormal_violation_stream_not_open(lungo_value *stream) {
    lungo_value *fields[1] = {stream};
    return lungo_value_ctor(2, fields, 1);
}
const lungo_value *capdagFormal_violation_stream_not_open_stream(const lungo_value *v) {
    return lungo_value_ctor_field(v, 2, 0);
}
lungo_value *capdagFormal_violation_chunk_out_of_place(lungo_value *stream, lungo_value *expected, lungo_value *got) {
    lungo_value *fields[3] = {stream, expected, got};
    return lungo_value_ctor(3, fields, 3);
}
const lungo_value *capdagFormal_violation_chunk_out_of_place_stream(const lungo_value *v) {
    return lungo_value_ctor_field(v, 3, 0);
}
const lungo_value *capdagFormal_violation_chunk_out_of_place_expected(const lungo_value *v) {
    return lungo_value_ctor_field(v, 3, 1);
}
const lungo_value *capdagFormal_violation_chunk_out_of_place_got(const lungo_value *v) {
    return lungo_value_ctor_field(v, 3, 2);
}
lungo_value *capdagFormal_violation_chunk_count_wrong(lungo_value *stream, lungo_value *sent, lungo_value *said) {
    lungo_value *fields[3] = {stream, sent, said};
    return lungo_value_ctor(4, fields, 3);
}
const lungo_value *capdagFormal_violation_chunk_count_wrong_stream(const lungo_value *v) {
    return lungo_value_ctor_field(v, 4, 0);
}
const lungo_value *capdagFormal_violation_chunk_count_wrong_sent(const lungo_value *v) {
    return lungo_value_ctor_field(v, 4, 1);
}
const lungo_value *capdagFormal_violation_chunk_count_wrong_said(const lungo_value *v) {
    return lungo_value_ctor_field(v, 4, 2);
}
lungo_value *capdagFormal_violation_end_with_open_stream(lungo_value *stream) {
    lungo_value *fields[1] = {stream};
    return lungo_value_ctor(5, fields, 1);
}
const lungo_value *capdagFormal_violation_end_with_open_stream_stream(const lungo_value *v) {
    return lungo_value_ctor_field(v, 5, 0);
}

lungo_type *capdagFormal_disposition_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 15, NULL, 0);
}
lungo_value *capdagFormal_disposition_route(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_disposition_straggler(void) {
    return lungo_value_ctor(1, NULL, 0);
}
lungo_value *capdagFormal_disposition_no_route(void) {
    return lungo_value_ctor(2, NULL, 0);
}

lungo_type *capdagFormal_terminal_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 16, NULL, 0);
}
lungo_value *capdagFormal_terminal_finished(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_terminal_failed(void) {
    return lungo_value_ctor(1, NULL, 0);
}
lungo_value *capdagFormal_terminal_cancelled(void) {
    return lungo_value_ctor(2, NULL, 0);
}
lungo_value *capdagFormal_terminal_master_died(void) {
    return lungo_value_ctor(3, NULL, 0);
}

lungo_type *capdagFormal_write_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 17, NULL, 0);
}
lungo_value *capdagFormal_write_send(lungo_value *ends) {
    lungo_value *fields[1] = {ends};
    return lungo_value_ctor(0, fields, 1);
}
const lungo_value *capdagFormal_write_send_ends(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
lungo_value *capdagFormal_write_suppress(void) {
    return lungo_value_ctor(1, NULL, 0);
}

lungo_type *capdagFormal_wf_cap_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 18, NULL, 0);
}
lungo_value *capdagFormal_wf_cap_mk(lungo_value *input, lungo_value *output, lungo_value *other, lungo_value *effect) {
    lungo_value *fields[4] = {input, output, other, effect};
    return lungo_value_ctor(0, fields, 4);
}
const lungo_value *capdagFormal_wf_cap_input(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_wf_cap_output(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}
const lungo_value *capdagFormal_wf_cap_other(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 2);
}
const lungo_value *capdagFormal_wf_cap_effect(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 3);
}

lungo_type *capdagFormal_effect_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 19, NULL, 0);
}
lungo_value *capdagFormal_effect_unspecified(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_effect_declared(void) {
    return lungo_value_ctor(1, NULL, 0);
}
lungo_value *capdagFormal_effect_none(void) {
    return lungo_value_ctor(2, NULL, 0);
}
lungo_value *capdagFormal_effect_patch(void) {
    return lungo_value_ctor(3, NULL, 0);
}

lungo_type *capdagFormal_wf_query_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 20, NULL, 0);
}
lungo_value *capdagFormal_wf_query_mk(lungo_value *input, lungo_value *output, lungo_value *tags, lungo_value *effect) {
    lungo_value *fields[4] = {input, output, tags, effect};
    return lungo_value_ctor(0, fields, 4);
}
const lungo_value *capdagFormal_wf_query_input(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_wf_query_output(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}
const lungo_value *capdagFormal_wf_query_tags(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 2);
}
const lungo_value *capdagFormal_wf_query_effect(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 3);
}

lungo_type *capdagFormal_wf_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 21, NULL, 0);
}

lungo_type *capdagFormal_grade_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 22, NULL, 0);
}
lungo_value *capdagFormal_grade_exact(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_grade_guaranteed(void) {
    return lungo_value_ctor(1, NULL, 0);
}
lungo_value *capdagFormal_grade_possible(void) {
    return lungo_value_ctor(2, NULL, 0);
}
lungo_value *capdagFormal_grade_none(void) {
    return lungo_value_ctor(3, NULL, 0);
}

lungo_type *capdagFormal_constraint_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 23, NULL, 0);
}
lungo_value *capdagFormal_constraint_missing(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_constraint_unconstrained(void) {
    return lungo_value_ctor(1, NULL, 0);
}
lungo_value *capdagFormal_constraint_optional_not(lungo_value *value) {
    lungo_value *fields[1] = {value};
    return lungo_value_ctor(2, fields, 1);
}
const lungo_value *capdagFormal_constraint_optional_not_value(const lungo_value *v) {
    return lungo_value_ctor_field(v, 2, 0);
}
lungo_value *capdagFormal_constraint_present(void) {
    return lungo_value_ctor(3, NULL, 0);
}
lungo_value *capdagFormal_constraint_present_not(lungo_value *value) {
    lungo_value *fields[1] = {value};
    return lungo_value_ctor(4, fields, 1);
}
const lungo_value *capdagFormal_constraint_present_not_value(const lungo_value *v) {
    return lungo_value_ctor_field(v, 4, 0);
}
lungo_value *capdagFormal_constraint_exact(lungo_value *value) {
    lungo_value *fields[1] = {value};
    return lungo_value_ctor(5, fields, 1);
}
const lungo_value *capdagFormal_constraint_exact_value(const lungo_value *v) {
    return lungo_value_ctor_field(v, 5, 0);
}
lungo_value *capdagFormal_constraint_absent(void) {
    return lungo_value_ctor(6, NULL, 0);
}

lungo_type *capdagFormal_pool_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 24, NULL, 0);
}
lungo_value *capdagFormal_pool_mk(lungo_value *name, lungo_value *capacity, lungo_value *active) {
    lungo_value *fields[3] = {name, capacity, active};
    return lungo_value_ctor(0, fields, 3);
}
const lungo_value *capdagFormal_pool_name(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 0);
}
const lungo_value *capdagFormal_pool_capacity(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 1);
}
const lungo_value *capdagFormal_pool_active(const lungo_value *v) {
    return lungo_value_ctor_field(v, 0, 2);
}

lungo_type *capdagFormal_wf_ask_type(void) {
    return lungo_type_inductive(capdagFormal__types(), 25, NULL, 0);
}
lungo_value *capdagFormal_wf_ask_unknown(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *capdagFormal_wf_ask_within(lungo_value *u) {
    lungo_value *fields[1] = {u};
    return lungo_value_ctor(1, fields, 1);
}
const lungo_value *capdagFormal_wf_ask_within_u(const lungo_value *v) {
    return lungo_value_ctor_field(v, 1, 0);
}
lungo_value *capdagFormal_wf_ask_covers(lungo_value *u) {
    lungo_value *fields[1] = {u};
    return lungo_value_ctor(2, fields, 1);
}
const lungo_value *capdagFormal_wf_ask_covers_u(const lungo_value *v) {
    return lungo_value_ctor_field(v, 2, 0);
}
lungo_value *capdagFormal_wf_ask_same(lungo_value *u) {
    lungo_value *fields[1] = {u};
    return lungo_value_ctor(3, fields, 1);
}
const lungo_value *capdagFormal_wf_ask_same_u(const lungo_value *v) {
    return lungo_value_ctor_field(v, 3, 0);
}

int32_t capdagFormal_acquire(const lungo_value *g, const lungo_value *n, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {g, n};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dacquire, sig_0, sizeof sig_0, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_close(const lungo_value *g, const lungo_value *reason, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {g, reason};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dclose, sig_1, sizeof sig_1, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_grant(const lungo_value *g, const lungo_value *n, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {g, n};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dgrant, sig_2, sizeof sig_2, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_gate_opened(const lungo_value *window, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {window};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dopened, sig_3, sizeof sig_3, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_window_arrive(const lungo_value *w, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {w};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_darrive, sig_4, sizeof sig_4, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_consume(const lungo_value *w, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {w};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dconsume, sig_5, sizeof sig_5, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_continued(const lungo_value *w, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {w};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dcontinued, sig_6, sizeof sig_6, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_flush(const lungo_value *w, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {w};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dflush, sig_7, sizeof sig_7, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_window_opened(const lungo_value *window, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {window};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dopened, sig_8, sizeof sig_8, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_grant_target(const lungo_value *streams, const lungo_value *named, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {streams, named};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dgrantTarget, sig_9, sizeof sig_9, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_negotiate(const lungo_value *ours, const lungo_value *theirs, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {ours, theirs};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dCredit_dnegotiate, sig_10, sizeof sig_10, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_code(const lungo_value *a, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {a};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_dcode, sig_11, sizeof sig_11, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_is_flow(const lungo_value *a, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {a};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_disFlow, sig_12, sizeof sig_12, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_is_terminal(const lungo_value *a, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {a};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_disTerminal, sig_13, sizeof sig_13, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_of_code(const lungo_value *a, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {a};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_dofCode, sig_14, sizeof sig_14, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_accept(const lungo_value *r, const lungo_value *seq, const lungo_value *limit, lungo_value **result, lungo_error **error) {
    const lungo_value *args[3] = {r, seq, limit};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dFlow_dReorder_daccept, sig_15, sizeof sig_15, NULL, 0, args, 3, result, error);
}

int32_t capdagFormal_start(lungo_value **result, lungo_error **error) {
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dFlow_dReorder_dstart, sig_16, sizeof sig_16, NULL, 0, NULL, 0, result, error);
}

int32_t capdagFormal_admit(const lungo_value *s, const lungo_value *ticket, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {s, ticket};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dadmit, sig_17, sizeof sig_17, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_admit_next(const lungo_value *s, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {s};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dadmitNext, sig_18, sizeof sig_18, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_state_arrive(const lungo_value *s, const lungo_value *chain, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {s, chain};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_darrive, sig_19, sizeof sig_19, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_empty(lungo_value **result, lungo_error **error) {
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dempty, sig_20, sizeof sig_20, NULL, 0, NULL, 0, result, error);
}

int32_t capdagFormal_has_room(const lungo_value *s, const lungo_value *chain, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {s, chain};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dhasRoom, sig_21, sizeof sig_21, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_held_back(const lungo_value *s, const lungo_value *name, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {s, name};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dheldBack, sig_22, sizeof sig_22, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_join(const lungo_value *s, const lungo_value *chain, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {s, chain};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_djoin, sig_23, sizeof sig_23, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_leave(const lungo_value *s, const lungo_value *ticket, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {s, ticket};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dleave, sig_24, sizeof sig_24, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_position(const lungo_value *s, const lungo_value *ticket, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {s, ticket};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dposition, sig_25, sizeof sig_25, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_release(const lungo_value *s, const lungo_value *chain, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {s, chain};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_drelease, sig_26, sizeof sig_26, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_set_capacity(const lungo_value *s, const lungo_value *name, const lungo_value *capacity, lungo_value **result, lungo_error **error) {
    const lungo_value *args[3] = {s, name, capacity};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dsetCapacity, sig_27, sizeof sig_27, NULL, 0, args, 3, result, error);
}

int32_t capdagFormal_advertised(const lungo_value *running, const lungo_value *pool, const lungo_value *configured, const lungo_value *available, lungo_value **result, lungo_error **error) {
    const lungo_value *args[4] = {running, pool, configured, available};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dadvertised, sig_28, sizeof sig_28, NULL, 0, args, 4, result, error);
}

int32_t capdagFormal_chain(const lungo_value *cap, const lungo_value *shared, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {cap, shared};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dchain, sig_29, sizeof sig_29, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_effective(const lungo_value *configured, const lungo_value *available, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {configured, available};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_deffective, sig_30, sizeof sig_30, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_patience(const lungo_value *unavailable_for, const lungo_value *grace, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {unavailable_for, grace};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dPools_dpatience, sig_31, sizeof sig_31, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_after(const lungo_value *p, const lungo_value *frame, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {p, frame};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dRequest_dPhase_dafter, sig_32, sizeof sig_32, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_check(const lungo_value *frames, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {frames};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dRequest_dcheck, sig_33, sizeof sig_33, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_dispose(const lungo_value *live, const lungo_value *ended_lately, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {live, ended_lately};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dRequest_ddispose, sig_34, sizeof sig_34, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_ledger(const lungo_value *remaining, const lungo_value *frame, const lungo_value *granted, lungo_value **result, lungo_error **error) {
    const lungo_value *args[3] = {remaining, frame, granted};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dRequest_dledger, sig_35, sizeof sig_35, NULL, 0, args, 3, result, error);
}

int32_t capdagFormal_terminal_of(const lungo_value *a, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {a};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dRequest_dterminalOf, sig_36, sizeof sig_36, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_write(const lungo_value *over, const lungo_value *frame, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {over, frame};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dBifaci_dRequest_dwrite, sig_37, sizeof sig_37, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_accepts(const lungo_value *pattern, const lungo_value *cap, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {pattern, cap};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_daccepts, sig_38, sizeof sig_38, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_comparable(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {a, b};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dcomparable, sig_39, sizeof sig_39, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_dispatch(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {candidate, request};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_ddispatch, sig_40, sizeof sig_40, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_effect_ok(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {candidate, request};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_deffectOk, sig_41, sizeof sig_41, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_equivalent(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {a, b};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dequivalent, sig_42, sizeof sig_42, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_flows(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {a, b};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dflows, sig_43, sizeof sig_43, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_may_dispatch(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {candidate, request};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dmayDispatch, sig_44, sizeof sig_44, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_may_flow(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {a, b};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dmayFlow, sig_45, sizeof sig_45, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_query_admits(const lungo_value *q, const lungo_value *c, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {q, c};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dqueryAdmits, sig_46, sizeof sig_46, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_query_between(const lungo_value *input, const lungo_value *output, const lungo_value *tags, lungo_value **result, lungo_error **error) {
    const lungo_value *args[3] = {input, output, tags};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dqueryBetween, sig_47, sizeof sig_47, NULL, 0, args, 3, result, error);
}

int32_t capdagFormal_query_consuming(const lungo_value *input, const lungo_value *tags, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {input, tags};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dqueryConsuming, sig_48, sizeof sig_48, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_query_grade(const lungo_value *q, const lungo_value *c, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {q, c};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dqueryGrade, sig_49, sizeof sig_49, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_query_may_admit(const lungo_value *q, const lungo_value *c, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {q, c};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dqueryMayAdmit, sig_50, sizeof sig_50, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_query_of_pattern(const lungo_value *p, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {p};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dqueryOfPattern, sig_51, sizeof sig_51, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_query_of_request(const lungo_value *r, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {r};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dqueryOfRequest, sig_52, sizeof sig_52, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_query_producing(const lungo_value *output, const lungo_value *tags, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {output, tags};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dqueryProducing, sig_53, sizeof sig_53, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_ranking_key(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {candidate, request};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_drankingKey, sig_54, sizeof sig_54, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_select(const lungo_value *candidates, const lungo_value *request, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {candidates, request};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dselect, sig_55, sizeof sig_55, NULL, 0, args, 2, result, error);
}

int32_t capdagFormal_specificity(const lungo_value *c, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {c};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_CapDAG_dExec_dspecificity, sig_56, sizeof sig_56, NULL, 0, args, 1, result, error);
}

int32_t capdagFormal_make(const lungo_value *scheme, const lungo_value *tags, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {scheme, tags};
    return lungo_invoke(capdagFormal__types(), capdagFormal__call_l_TaggedUrn_dExec_dmake, sig_57, sizeof sig_57, NULL, 0, args, 2, result, error);
}

