/* Generated by lungo 1.69.2868 from Lean 4.34.1 for program capdagFormal. Do not edit. */
#ifndef CAPDAGFORMAL_ENTRIES_H
#define CAPDAGFORMAL_ENTRIES_H
#include "lungo.h"
const lungo_types *capdagFormal__types(void);
void capdagFormal__set_host_extern(size_t index, uint64_t callback);
int32_t capdagFormal__call_l_CapDAG_dExec_daccepts(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t capdagFormal__call_l_CapDAG_dExec_dcomparable(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t capdagFormal__call_l_CapDAG_dExec_ddispatch(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t capdagFormal__call_l_CapDAG_dExec_deffectOk(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t capdagFormal__call_l_CapDAG_dExec_dequivalent(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t capdagFormal__call_l_CapDAG_dExec_drankingKey(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t capdagFormal__call_l_CapDAG_dExec_dselect(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t capdagFormal__call_l_CapDAG_dExec_dspecificity(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t capdagFormal__call_l_TaggedUrn_dExec_dmake(const uint8_t *input, size_t len, lungo_buffer *out);
#endif /* CAPDAGFORMAL_ENTRIES_H */
