/* Generated by lungo 1.84.11 from Lean 4.34.1 for program capdagFormal. Do not edit. */
#ifndef CAPDAGFORMAL_H
#define CAPDAGFORMAL_H

#include "lungo.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initializes the program; every function initializes it on first use. */
void capdagFormal_initialize(void);

/* CapDAG.Bifaci.Credit.Gate */
#define CAPDAGFORMAL_GATE_FINGERPRINT "b10dc9a4cff1977f4f6a2c415147f497f98740255d0158fb2b3a2a99d4d1b135"
lungo_type *capdagFormal_gate_type(void);
#define CAPDAGFORMAL_GATE_MK 0
/* CapDAG.Bifaci.Credit.Gate.mk; takes ownership of the fields. */
lungo_value *capdagFormal_gate_mk(lungo_value *available, lungo_value *closed);
/* Field available of CapDAG.Bifaci.Credit.Gate.mk (borrowed). */
const lungo_value *capdagFormal_gate_available(const lungo_value *v);
/* Field closed of CapDAG.Bifaci.Credit.Gate.mk (borrowed). */
const lungo_value *capdagFormal_gate_closed(const lungo_value *v);

/* CapDAG.Bifaci.Credit.Acquire */
#define CAPDAGFORMAL_ACQUIRE_FINGERPRINT "0dabbf62c4dad8c3f81811acc80f5c789d25191897bb2621de51b5f94e54a4c9"
lungo_type *capdagFormal_acquire_type(void);
#define CAPDAGFORMAL_ACQUIRE_ACQUIRED 0
/* CapDAG.Bifaci.Credit.Acquire.acquired; takes ownership of the fields. */
lungo_value *capdagFormal_acquire_acquired(lungo_value *gate);
/* Field gate of CapDAG.Bifaci.Credit.Acquire.acquired (borrowed). */
const lungo_value *capdagFormal_acquire_acquired_gate(const lungo_value *v);
#define CAPDAGFORMAL_ACQUIRE_WAIT 1
/* CapDAG.Bifaci.Credit.Acquire.wait; takes ownership of the fields. */
lungo_value *capdagFormal_acquire_wait(void);
#define CAPDAGFORMAL_ACQUIRE_CLOSED 2
/* CapDAG.Bifaci.Credit.Acquire.closed; takes ownership of the fields. */
lungo_value *capdagFormal_acquire_closed(lungo_value *reason);
/* Field reason of CapDAG.Bifaci.Credit.Acquire.closed (borrowed). */
const lungo_value *capdagFormal_acquire_closed_reason(const lungo_value *v);

/* CapDAG.Bifaci.Credit.Window */
#define CAPDAGFORMAL_WINDOW_FINGERPRINT "28df89763b22214ef57dfd7f1a3c0da786ff78af9768fe453cd451870749b6fe"
lungo_type *capdagFormal_window_type(void);
#define CAPDAGFORMAL_WINDOW_MK 0
/* CapDAG.Bifaci.Credit.Window.mk; takes ownership of the fields. */
lungo_value *capdagFormal_window_mk(lungo_value *remaining, lungo_value *pending, lungo_value *batch);
/* Field remaining of CapDAG.Bifaci.Credit.Window.mk (borrowed). */
const lungo_value *capdagFormal_window_remaining(const lungo_value *v);
/* Field pending of CapDAG.Bifaci.Credit.Window.mk (borrowed). */
const lungo_value *capdagFormal_window_pending(const lungo_value *v);
/* Field batch of CapDAG.Bifaci.Credit.Window.mk (borrowed). */
const lungo_value *capdagFormal_window_batch(const lungo_value *v);

/* CapDAG.Bifaci.Credit.Arrival */
#define CAPDAGFORMAL_CREDIT_ARRIVAL_FINGERPRINT "940f01cf50eb8b763b9f44cc84753fcdbc65fbc0f816ab279408e74208649797"
lungo_type *capdagFormal_credit_arrival_type(void);
#define CAPDAGFORMAL_CREDIT_ARRIVAL_ACCEPTED 0
/* CapDAG.Bifaci.Credit.Arrival.accepted; takes ownership of the fields. */
lungo_value *capdagFormal_credit_arrival_accepted(lungo_value *window);
/* Field window of CapDAG.Bifaci.Credit.Arrival.accepted (borrowed). */
const lungo_value *capdagFormal_credit_arrival_accepted_window(const lungo_value *v);
#define CAPDAGFORMAL_CREDIT_ARRIVAL_VIOLATION 1
/* CapDAG.Bifaci.Credit.Arrival.violation; takes ownership of the fields. */
lungo_value *capdagFormal_credit_arrival_violation(void);

/* CapDAG.Bifaci.Credit.Granted */
#define CAPDAGFORMAL_GRANTED_FINGERPRINT "47f8d3e63e9aaf7c4b602f781afce57fc832e3d4d645c6adabd25c461abed233"
lungo_type *capdagFormal_granted_type(void);
#define CAPDAGFORMAL_GRANTED_MK 0
/* CapDAG.Bifaci.Credit.Granted.mk; takes ownership of the fields. */
lungo_value *capdagFormal_granted_mk(lungo_value *window, lungo_value *grant);
/* Field window of CapDAG.Bifaci.Credit.Granted.mk (borrowed). */
const lungo_value *capdagFormal_granted_window(const lungo_value *v);
/* Field grant of CapDAG.Bifaci.Credit.Granted.mk (borrowed). */
const lungo_value *capdagFormal_granted_grant(const lungo_value *v);

/* CapDAG.Bifaci.Flow.FrameType */
#define CAPDAGFORMAL_FRAME_TYPE_FINGERPRINT "3d6742b864aeb68cf6add586acfcd1a9663a3816d718f8d8aadc3c5e3dab3e2f"
lungo_type *capdagFormal_frame_type_type(void);
#define CAPDAGFORMAL_FRAME_TYPE_HELLO 0
/* CapDAG.Bifaci.Flow.FrameType.hello; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_hello(void);
#define CAPDAGFORMAL_FRAME_TYPE_REQ 1
/* CapDAG.Bifaci.Flow.FrameType.req; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_req(void);
#define CAPDAGFORMAL_FRAME_TYPE_CHUNK 2
/* CapDAG.Bifaci.Flow.FrameType.chunk; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_chunk(void);
#define CAPDAGFORMAL_FRAME_TYPE_FIN 3
/* CapDAG.Bifaci.Flow.FrameType.fin; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_fin(void);
#define CAPDAGFORMAL_FRAME_TYPE_LOG 4
/* CapDAG.Bifaci.Flow.FrameType.log; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_log(void);
#define CAPDAGFORMAL_FRAME_TYPE_ERR 5
/* CapDAG.Bifaci.Flow.FrameType.err; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_err(void);
#define CAPDAGFORMAL_FRAME_TYPE_HEARTBEAT 6
/* CapDAG.Bifaci.Flow.FrameType.heartbeat; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_heartbeat(void);
#define CAPDAGFORMAL_FRAME_TYPE_STREAM_START 7
/* CapDAG.Bifaci.Flow.FrameType.streamStart; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_stream_start(void);
#define CAPDAGFORMAL_FRAME_TYPE_STREAM_END 8
/* CapDAG.Bifaci.Flow.FrameType.streamEnd; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_stream_end(void);
#define CAPDAGFORMAL_FRAME_TYPE_RELAY_NOTIFY 9
/* CapDAG.Bifaci.Flow.FrameType.relayNotify; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_relay_notify(void);
#define CAPDAGFORMAL_FRAME_TYPE_RELAY_STATE 10
/* CapDAG.Bifaci.Flow.FrameType.relayState; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_relay_state(void);
#define CAPDAGFORMAL_FRAME_TYPE_CANCEL 11
/* CapDAG.Bifaci.Flow.FrameType.cancel; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_cancel(void);
#define CAPDAGFORMAL_FRAME_TYPE_CREDIT 12
/* CapDAG.Bifaci.Flow.FrameType.credit; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_credit(void);
#define CAPDAGFORMAL_FRAME_TYPE_CLOSE_STREAM 13
/* CapDAG.Bifaci.Flow.FrameType.closeStream; takes ownership of the fields. */
lungo_value *capdagFormal_frame_type_close_stream(void);

/* CapDAG.Bifaci.Flow.Reorder */
#define CAPDAGFORMAL_REORDER_FINGERPRINT "d1e8b655f24db5e8b2348d6d41084a5c454346eb0a81fcf11b671432e72291bf"
lungo_type *capdagFormal_reorder_type(void);
#define CAPDAGFORMAL_REORDER_MK 0
/* CapDAG.Bifaci.Flow.Reorder.mk; takes ownership of the fields. */
lungo_value *capdagFormal_reorder_mk(lungo_value *expected, lungo_value *held);
/* Field expected of CapDAG.Bifaci.Flow.Reorder.mk (borrowed). */
const lungo_value *capdagFormal_reorder_expected(const lungo_value *v);
/* Field held of CapDAG.Bifaci.Flow.Reorder.mk (borrowed). */
const lungo_value *capdagFormal_reorder_held(const lungo_value *v);

/* CapDAG.Bifaci.Flow.Accepted */
#define CAPDAGFORMAL_ACCEPTED_FINGERPRINT "a821d7a044f52a71dfd932fff60d2f3560ce5197658283853a56fb54aa96b69b"
lungo_type *capdagFormal_accepted_type(void);
#define CAPDAGFORMAL_ACCEPTED_DELIVER 0
/* CapDAG.Bifaci.Flow.Accepted.deliver; takes ownership of the fields. */
lungo_value *capdagFormal_accepted_deliver(lungo_value *flow, lungo_value *seqs);
/* Field flow of CapDAG.Bifaci.Flow.Accepted.deliver (borrowed). */
const lungo_value *capdagFormal_accepted_deliver_flow(const lungo_value *v);
/* Field seqs of CapDAG.Bifaci.Flow.Accepted.deliver (borrowed). */
const lungo_value *capdagFormal_accepted_deliver_seqs(const lungo_value *v);
#define CAPDAGFORMAL_ACCEPTED_HOLD 1
/* CapDAG.Bifaci.Flow.Accepted.hold; takes ownership of the fields. */
lungo_value *capdagFormal_accepted_hold(lungo_value *flow);
/* Field flow of CapDAG.Bifaci.Flow.Accepted.hold (borrowed). */
const lungo_value *capdagFormal_accepted_hold_flow(const lungo_value *v);
#define CAPDAGFORMAL_ACCEPTED_STALE 2
/* CapDAG.Bifaci.Flow.Accepted.stale; takes ownership of the fields. */
lungo_value *capdagFormal_accepted_stale(void);
#define CAPDAGFORMAL_ACCEPTED_DUPLICATE 3
/* CapDAG.Bifaci.Flow.Accepted.duplicate; takes ownership of the fields. */
lungo_value *capdagFormal_accepted_duplicate(void);
#define CAPDAGFORMAL_ACCEPTED_OVERFLOW 4
/* CapDAG.Bifaci.Flow.Accepted.overflow; takes ownership of the fields. */
lungo_value *capdagFormal_accepted_overflow(void);

/* CapDAG.Bifaci.Pools.State */
#define CAPDAGFORMAL_STATE_FINGERPRINT "20f7299c188d09234cda39e9cc356242e2b5bc56a09cf819d12d7f50fa24989b"
lungo_type *capdagFormal_state_type(void);
#define CAPDAGFORMAL_STATE_MK 0
/* CapDAG.Bifaci.Pools.State.mk; takes ownership of the fields. */
lungo_value *capdagFormal_state_mk(lungo_value *pools, lungo_value *queue, lungo_value *next);
/* Field pools of CapDAG.Bifaci.Pools.State.mk (borrowed). */
const lungo_value *capdagFormal_state_pools(const lungo_value *v);
/* Field queue of CapDAG.Bifaci.Pools.State.mk (borrowed). */
const lungo_value *capdagFormal_state_queue(const lungo_value *v);
/* Field next of CapDAG.Bifaci.Pools.State.mk (borrowed). */
const lungo_value *capdagFormal_state_next(const lungo_value *v);

/* CapDAG.Bifaci.Pools.Waiter */
#define CAPDAGFORMAL_WAITER_FINGERPRINT "48d81c7e41df114e88751bb5c1f4a84c16bac3ad28d8eacba141d45f92c79da0"
lungo_type *capdagFormal_waiter_type(void);
#define CAPDAGFORMAL_WAITER_MK 0
/* CapDAG.Bifaci.Pools.Waiter.mk; takes ownership of the fields. */
lungo_value *capdagFormal_waiter_mk(lungo_value *ticket, lungo_value *chain);
/* Field ticket of CapDAG.Bifaci.Pools.Waiter.mk (borrowed). */
const lungo_value *capdagFormal_waiter_ticket(const lungo_value *v);
/* Field chain of CapDAG.Bifaci.Pools.Waiter.mk (borrowed). */
const lungo_value *capdagFormal_waiter_chain(const lungo_value *v);

/* CapDAG.Bifaci.Pools.Arrival */
#define CAPDAGFORMAL_POOLS_ARRIVAL_FINGERPRINT "6bee196c56c330c4ef348f4dd5a68558b2d19105592969cc64a0e7150bd22451"
lungo_type *capdagFormal_pools_arrival_type(void);
#define CAPDAGFORMAL_POOLS_ARRIVAL_ADMITTED 0
/* CapDAG.Bifaci.Pools.Arrival.admitted; takes ownership of the fields. */
lungo_value *capdagFormal_pools_arrival_admitted(lungo_value *state);
/* Field state of CapDAG.Bifaci.Pools.Arrival.admitted (borrowed). */
const lungo_value *capdagFormal_pools_arrival_admitted_state(const lungo_value *v);
#define CAPDAGFORMAL_POOLS_ARRIVAL_QUEUED 1
/* CapDAG.Bifaci.Pools.Arrival.queued; takes ownership of the fields. */
lungo_value *capdagFormal_pools_arrival_queued(lungo_value *state, lungo_value *ticket, lungo_value *position);
/* Field state of CapDAG.Bifaci.Pools.Arrival.queued (borrowed). */
const lungo_value *capdagFormal_pools_arrival_queued_state(const lungo_value *v);
/* Field ticket of CapDAG.Bifaci.Pools.Arrival.queued (borrowed). */
const lungo_value *capdagFormal_pools_arrival_queued_ticket(const lungo_value *v);
/* Field position of CapDAG.Bifaci.Pools.Arrival.queued (borrowed). */
const lungo_value *capdagFormal_pools_arrival_queued_position(const lungo_value *v);
#define CAPDAGFORMAL_POOLS_ARRIVAL_UNKNOWN_POOL 2
/* CapDAG.Bifaci.Pools.Arrival.unknownPool; takes ownership of the fields. */
lungo_value *capdagFormal_pools_arrival_unknown_pool(lungo_value *name);
/* Field name of CapDAG.Bifaci.Pools.Arrival.unknownPool (borrowed). */
const lungo_value *capdagFormal_pools_arrival_unknown_pool_name(const lungo_value *v);

/* CapDAG.Bifaci.Pools.Patience */
#define CAPDAGFORMAL_PATIENCE_FINGERPRINT "d32e3427e590ca6002e38cface52d020c7df74603f952bf568401f7291d5648c"
lungo_type *capdagFormal_patience_type(void);
#define CAPDAGFORMAL_PATIENCE_UNBOUNDED 0
/* CapDAG.Bifaci.Pools.Patience.unbounded; takes ownership of the fields. */
lungo_value *capdagFormal_patience_unbounded(void);
#define CAPDAGFORMAL_PATIENCE_AT_MOST 1
/* CapDAG.Bifaci.Pools.Patience.atMost; takes ownership of the fields. */
lungo_value *capdagFormal_patience_at_most(lungo_value *remaining);
/* Field remaining of CapDAG.Bifaci.Pools.Patience.atMost (borrowed). */
const lungo_value *capdagFormal_patience_at_most_remaining(const lungo_value *v);
#define CAPDAGFORMAL_PATIENCE_EXHAUSTED 2
/* CapDAG.Bifaci.Pools.Patience.exhausted; takes ownership of the fields. */
lungo_value *capdagFormal_patience_exhausted(void);

/* CapDAG.Bifaci.Request.Phase */
#define CAPDAGFORMAL_PHASE_FINGERPRINT "7407437b58ce033618bf82341b13aaa9661d29a5a9b0f1bf1547ea0bfcfd8374"
lungo_type *capdagFormal_phase_type(void);
#define CAPDAGFORMAL_PHASE_CREATED 0
/* CapDAG.Bifaci.Request.Phase.created; takes ownership of the fields. */
lungo_value *capdagFormal_phase_created(void);
#define CAPDAGFORMAL_PHASE_STREAMING 1
/* CapDAG.Bifaci.Request.Phase.streaming; takes ownership of the fields. */
lungo_value *capdagFormal_phase_streaming(void);

/* CapDAG.Bifaci.Request.Emitted */
#define CAPDAGFORMAL_EMITTED_FINGERPRINT "97a274be14c5baecf9c50243d3651da838c5de4375366d4102cbcff85fb211c8"
lungo_type *capdagFormal_emitted_type(void);
#define CAPDAGFORMAL_EMITTED_STREAM_START 0
/* CapDAG.Bifaci.Request.Emitted.streamStart; takes ownership of the fields. */
lungo_value *capdagFormal_emitted_stream_start(lungo_value *stream);
/* Field stream of CapDAG.Bifaci.Request.Emitted.streamStart (borrowed). */
const lungo_value *capdagFormal_emitted_stream_start_stream(const lungo_value *v);
#define CAPDAGFORMAL_EMITTED_CHUNK 1
/* CapDAG.Bifaci.Request.Emitted.chunk; takes ownership of the fields. */
lungo_value *capdagFormal_emitted_chunk(lungo_value *stream, lungo_value *index);
/* Field stream of CapDAG.Bifaci.Request.Emitted.chunk (borrowed). */
const lungo_value *capdagFormal_emitted_chunk_stream(const lungo_value *v);
/* Field index of CapDAG.Bifaci.Request.Emitted.chunk (borrowed). */
const lungo_value *capdagFormal_emitted_chunk_index(const lungo_value *v);
#define CAPDAGFORMAL_EMITTED_STREAM_END 2
/* CapDAG.Bifaci.Request.Emitted.streamEnd; takes ownership of the fields. */
lungo_value *capdagFormal_emitted_stream_end(lungo_value *stream, lungo_value *count);
/* Field stream of CapDAG.Bifaci.Request.Emitted.streamEnd (borrowed). */
const lungo_value *capdagFormal_emitted_stream_end_stream(const lungo_value *v);
/* Field count of CapDAG.Bifaci.Request.Emitted.streamEnd (borrowed). */
const lungo_value *capdagFormal_emitted_stream_end_count(const lungo_value *v);
#define CAPDAGFORMAL_EMITTED_FIN 3
/* CapDAG.Bifaci.Request.Emitted.fin; takes ownership of the fields. */
lungo_value *capdagFormal_emitted_fin(void);
#define CAPDAGFORMAL_EMITTED_ERR 4
/* CapDAG.Bifaci.Request.Emitted.err; takes ownership of the fields. */
lungo_value *capdagFormal_emitted_err(void);
#define CAPDAGFORMAL_EMITTED_OTHER 5
/* CapDAG.Bifaci.Request.Emitted.other; takes ownership of the fields. */
lungo_value *capdagFormal_emitted_other(void);

/* CapDAG.Bifaci.Request.Violation */
#define CAPDAGFORMAL_VIOLATION_FINGERPRINT "203fb2fc4f8ff3c79b70871b4274852e742adf97c3cc4e6631439ec66d838f09"
lungo_type *capdagFormal_violation_type(void);
#define CAPDAGFORMAL_VIOLATION_AFTER_END 0
/* CapDAG.Bifaci.Request.Violation.afterEnd; takes ownership of the fields. */
lungo_value *capdagFormal_violation_after_end(void);
#define CAPDAGFORMAL_VIOLATION_STREAM_RESTARTED 1
/* CapDAG.Bifaci.Request.Violation.streamRestarted; takes ownership of the fields. */
lungo_value *capdagFormal_violation_stream_restarted(lungo_value *stream);
/* Field stream of CapDAG.Bifaci.Request.Violation.streamRestarted (borrowed). */
const lungo_value *capdagFormal_violation_stream_restarted_stream(const lungo_value *v);
#define CAPDAGFORMAL_VIOLATION_STREAM_NOT_OPEN 2
/* CapDAG.Bifaci.Request.Violation.streamNotOpen; takes ownership of the fields. */
lungo_value *capdagFormal_violation_stream_not_open(lungo_value *stream);
/* Field stream of CapDAG.Bifaci.Request.Violation.streamNotOpen (borrowed). */
const lungo_value *capdagFormal_violation_stream_not_open_stream(const lungo_value *v);
#define CAPDAGFORMAL_VIOLATION_CHUNK_OUT_OF_PLACE 3
/* CapDAG.Bifaci.Request.Violation.chunkOutOfPlace; takes ownership of the fields. */
lungo_value *capdagFormal_violation_chunk_out_of_place(lungo_value *stream, lungo_value *expected, lungo_value *got);
/* Field stream of CapDAG.Bifaci.Request.Violation.chunkOutOfPlace (borrowed). */
const lungo_value *capdagFormal_violation_chunk_out_of_place_stream(const lungo_value *v);
/* Field expected of CapDAG.Bifaci.Request.Violation.chunkOutOfPlace (borrowed). */
const lungo_value *capdagFormal_violation_chunk_out_of_place_expected(const lungo_value *v);
/* Field got of CapDAG.Bifaci.Request.Violation.chunkOutOfPlace (borrowed). */
const lungo_value *capdagFormal_violation_chunk_out_of_place_got(const lungo_value *v);
#define CAPDAGFORMAL_VIOLATION_CHUNK_COUNT_WRONG 4
/* CapDAG.Bifaci.Request.Violation.chunkCountWrong; takes ownership of the fields. */
lungo_value *capdagFormal_violation_chunk_count_wrong(lungo_value *stream, lungo_value *sent, lungo_value *said);
/* Field stream of CapDAG.Bifaci.Request.Violation.chunkCountWrong (borrowed). */
const lungo_value *capdagFormal_violation_chunk_count_wrong_stream(const lungo_value *v);
/* Field sent of CapDAG.Bifaci.Request.Violation.chunkCountWrong (borrowed). */
const lungo_value *capdagFormal_violation_chunk_count_wrong_sent(const lungo_value *v);
/* Field said of CapDAG.Bifaci.Request.Violation.chunkCountWrong (borrowed). */
const lungo_value *capdagFormal_violation_chunk_count_wrong_said(const lungo_value *v);
#define CAPDAGFORMAL_VIOLATION_END_WITH_OPEN_STREAM 5
/* CapDAG.Bifaci.Request.Violation.endWithOpenStream; takes ownership of the fields. */
lungo_value *capdagFormal_violation_end_with_open_stream(lungo_value *stream);
/* Field stream of CapDAG.Bifaci.Request.Violation.endWithOpenStream (borrowed). */
const lungo_value *capdagFormal_violation_end_with_open_stream_stream(const lungo_value *v);

/* CapDAG.Bifaci.Request.Disposition */
#define CAPDAGFORMAL_DISPOSITION_FINGERPRINT "540307dfb6e509ccde4b894c69566edd1f3f9c3223b9325e97ee91b20d0fb82f"
lungo_type *capdagFormal_disposition_type(void);
#define CAPDAGFORMAL_DISPOSITION_ROUTE 0
/* CapDAG.Bifaci.Request.Disposition.route; takes ownership of the fields. */
lungo_value *capdagFormal_disposition_route(void);
#define CAPDAGFORMAL_DISPOSITION_STRAGGLER 1
/* CapDAG.Bifaci.Request.Disposition.straggler; takes ownership of the fields. */
lungo_value *capdagFormal_disposition_straggler(void);
#define CAPDAGFORMAL_DISPOSITION_NO_ROUTE 2
/* CapDAG.Bifaci.Request.Disposition.noRoute; takes ownership of the fields. */
lungo_value *capdagFormal_disposition_no_route(void);

/* CapDAG.Bifaci.Request.Terminal */
#define CAPDAGFORMAL_TERMINAL_FINGERPRINT "3597c3196cef5e4468b5449eb0da09af414bb8c3aa40d92b027089f6ae81c870"
lungo_type *capdagFormal_terminal_type(void);
#define CAPDAGFORMAL_TERMINAL_FINISHED 0
/* CapDAG.Bifaci.Request.Terminal.finished; takes ownership of the fields. */
lungo_value *capdagFormal_terminal_finished(void);
#define CAPDAGFORMAL_TERMINAL_FAILED 1
/* CapDAG.Bifaci.Request.Terminal.failed; takes ownership of the fields. */
lungo_value *capdagFormal_terminal_failed(void);
#define CAPDAGFORMAL_TERMINAL_CANCELLED 2
/* CapDAG.Bifaci.Request.Terminal.cancelled; takes ownership of the fields. */
lungo_value *capdagFormal_terminal_cancelled(void);
#define CAPDAGFORMAL_TERMINAL_MASTER_DIED 3
/* CapDAG.Bifaci.Request.Terminal.masterDied; takes ownership of the fields. */
lungo_value *capdagFormal_terminal_master_died(void);

/* CapDAG.Bifaci.Request.Write */
#define CAPDAGFORMAL_WRITE_FINGERPRINT "9ae21282903c8131c25ca1cc527e51fd1fa5137aa77c9ef4f3d091e9415a109a"
lungo_type *capdagFormal_write_type(void);
#define CAPDAGFORMAL_WRITE_SEND 0
/* CapDAG.Bifaci.Request.Write.send; takes ownership of the fields. */
lungo_value *capdagFormal_write_send(lungo_value *ends);
/* Field ends of CapDAG.Bifaci.Request.Write.send (borrowed). */
const lungo_value *capdagFormal_write_send_ends(const lungo_value *v);
#define CAPDAGFORMAL_WRITE_SUPPRESS 1
/* CapDAG.Bifaci.Request.Write.suppress; takes ownership of the fields. */
lungo_value *capdagFormal_write_suppress(void);

/* CapDAG.Exec.WfCap */
#define CAPDAGFORMAL_WF_CAP_FINGERPRINT "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830"
lungo_type *capdagFormal_wf_cap_type(void);
#define CAPDAGFORMAL_WF_CAP_MK 0
/* CapDAG.Exec.WfCap.mk; takes ownership of the fields. */
lungo_value *capdagFormal_wf_cap_mk(lungo_value *input, lungo_value *output, lungo_value *other, lungo_value *effect);
/* Field input of CapDAG.Exec.WfCap.mk (borrowed). */
const lungo_value *capdagFormal_wf_cap_input(const lungo_value *v);
/* Field output of CapDAG.Exec.WfCap.mk (borrowed). */
const lungo_value *capdagFormal_wf_cap_output(const lungo_value *v);
/* Field other of CapDAG.Exec.WfCap.mk (borrowed). */
const lungo_value *capdagFormal_wf_cap_other(const lungo_value *v);
/* Field effect of CapDAG.Exec.WfCap.mk (borrowed). */
const lungo_value *capdagFormal_wf_cap_effect(const lungo_value *v);

/* CapDAG.Effect */
#define CAPDAGFORMAL_EFFECT_FINGERPRINT "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477"
lungo_type *capdagFormal_effect_type(void);
#define CAPDAGFORMAL_EFFECT_UNSPECIFIED 0
/* CapDAG.Effect.unspecified; takes ownership of the fields. */
lungo_value *capdagFormal_effect_unspecified(void);
#define CAPDAGFORMAL_EFFECT_DECLARED 1
/* CapDAG.Effect.declared; takes ownership of the fields. */
lungo_value *capdagFormal_effect_declared(void);
#define CAPDAGFORMAL_EFFECT_NONE 2
/* CapDAG.Effect.none; takes ownership of the fields. */
lungo_value *capdagFormal_effect_none(void);
#define CAPDAGFORMAL_EFFECT_PATCH 3
/* CapDAG.Effect.patch; takes ownership of the fields. */
lungo_value *capdagFormal_effect_patch(void);

/* CapDAG.Exec.WfQuery */
#define CAPDAGFORMAL_WF_QUERY_FINGERPRINT "e734861d70e3177f6563c4492990bb65131f0450b8dfc62071eb61b6c5f08b8e"
lungo_type *capdagFormal_wf_query_type(void);
#define CAPDAGFORMAL_WF_QUERY_MK 0
/* CapDAG.Exec.WfQuery.mk; takes ownership of the fields. */
lungo_value *capdagFormal_wf_query_mk(lungo_value *input, lungo_value *output, lungo_value *tags, lungo_value *effect);
/* Field input of CapDAG.Exec.WfQuery.mk (borrowed). */
const lungo_value *capdagFormal_wf_query_input(const lungo_value *v);
/* Field output of CapDAG.Exec.WfQuery.mk (borrowed). */
const lungo_value *capdagFormal_wf_query_output(const lungo_value *v);
/* Field tags of CapDAG.Exec.WfQuery.mk (borrowed). */
const lungo_value *capdagFormal_wf_query_tags(const lungo_value *v);
/* Field effect of CapDAG.Exec.WfQuery.mk (borrowed). */
const lungo_value *capdagFormal_wf_query_effect(const lungo_value *v);

/* TaggedUrn.Exec.Wf */
#define CAPDAGFORMAL_WF_FINGERPRINT "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785"
lungo_type *capdagFormal_wf_type(void);

/* CapDAG.Grade */
#define CAPDAGFORMAL_GRADE_FINGERPRINT "0a2a20a14d9ecca6121343df2d8a7f2478b3e837710ed522ed385d35efdf46f2"
lungo_type *capdagFormal_grade_type(void);
#define CAPDAGFORMAL_GRADE_EXACT 0
/* CapDAG.Grade.exact; takes ownership of the fields. */
lungo_value *capdagFormal_grade_exact(void);
#define CAPDAGFORMAL_GRADE_GUARANTEED 1
/* CapDAG.Grade.guaranteed; takes ownership of the fields. */
lungo_value *capdagFormal_grade_guaranteed(void);
#define CAPDAGFORMAL_GRADE_POSSIBLE 2
/* CapDAG.Grade.possible; takes ownership of the fields. */
lungo_value *capdagFormal_grade_possible(void);
#define CAPDAGFORMAL_GRADE_NONE 3
/* CapDAG.Grade.none; takes ownership of the fields. */
lungo_value *capdagFormal_grade_none(void);

/* TaggedUrn.Constraint */
#define CAPDAGFORMAL_CONSTRAINT_FINGERPRINT "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"
lungo_type *capdagFormal_constraint_type(void);
#define CAPDAGFORMAL_CONSTRAINT_MISSING 0
/* TaggedUrn.Constraint.missing; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_missing(void);
#define CAPDAGFORMAL_CONSTRAINT_UNCONSTRAINED 1
/* TaggedUrn.Constraint.unconstrained; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_unconstrained(void);
#define CAPDAGFORMAL_CONSTRAINT_OPTIONAL_NOT 2
/* TaggedUrn.Constraint.optionalNot; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_optional_not(lungo_value *value);
/* Field value of TaggedUrn.Constraint.optionalNot (borrowed). */
const lungo_value *capdagFormal_constraint_optional_not_value(const lungo_value *v);
#define CAPDAGFORMAL_CONSTRAINT_PRESENT 3
/* TaggedUrn.Constraint.present; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_present(void);
#define CAPDAGFORMAL_CONSTRAINT_PRESENT_NOT 4
/* TaggedUrn.Constraint.presentNot; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_present_not(lungo_value *value);
/* Field value of TaggedUrn.Constraint.presentNot (borrowed). */
const lungo_value *capdagFormal_constraint_present_not_value(const lungo_value *v);
#define CAPDAGFORMAL_CONSTRAINT_EXACT 5
/* TaggedUrn.Constraint.exact; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_exact(lungo_value *value);
/* Field value of TaggedUrn.Constraint.exact (borrowed). */
const lungo_value *capdagFormal_constraint_exact_value(const lungo_value *v);
#define CAPDAGFORMAL_CONSTRAINT_ABSENT 6
/* TaggedUrn.Constraint.absent; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_absent(void);

/* CapDAG.Bifaci.Pools.Pool */
#define CAPDAGFORMAL_POOL_FINGERPRINT "60bca9d670886c7830c76779ad692b4fbb6e4e30c0ce6b3e9d5a91a9b5b7b1e6"
lungo_type *capdagFormal_pool_type(void);
#define CAPDAGFORMAL_POOL_MK 0
/* CapDAG.Bifaci.Pools.Pool.mk; takes ownership of the fields. */
lungo_value *capdagFormal_pool_mk(lungo_value *name, lungo_value *capacity, lungo_value *active);
/* Field name of CapDAG.Bifaci.Pools.Pool.mk (borrowed). */
const lungo_value *capdagFormal_pool_name(const lungo_value *v);
/* Field capacity of CapDAG.Bifaci.Pools.Pool.mk (borrowed). */
const lungo_value *capdagFormal_pool_capacity(const lungo_value *v);
/* Field active of CapDAG.Bifaci.Pools.Pool.mk (borrowed). */
const lungo_value *capdagFormal_pool_active(const lungo_value *v);

/* CapDAG.Exec.WfAsk */
#define CAPDAGFORMAL_WF_ASK_FINGERPRINT "d286477c7abc4e6bc6ee2d06889372b71a5bb06605b592ebabb6ad3eaf71b952"
lungo_type *capdagFormal_wf_ask_type(void);
#define CAPDAGFORMAL_WF_ASK_UNKNOWN 0
/* CapDAG.Exec.WfAsk.unknown; takes ownership of the fields. */
lungo_value *capdagFormal_wf_ask_unknown(void);
#define CAPDAGFORMAL_WF_ASK_WITHIN 1
/* CapDAG.Exec.WfAsk.within; takes ownership of the fields. */
lungo_value *capdagFormal_wf_ask_within(lungo_value *u);
/* Field u of CapDAG.Exec.WfAsk.within (borrowed). */
const lungo_value *capdagFormal_wf_ask_within_u(const lungo_value *v);
#define CAPDAGFORMAL_WF_ASK_COVERS 2
/* CapDAG.Exec.WfAsk.covers; takes ownership of the fields. */
lungo_value *capdagFormal_wf_ask_covers(lungo_value *u);
/* Field u of CapDAG.Exec.WfAsk.covers (borrowed). */
const lungo_value *capdagFormal_wf_ask_covers_u(const lungo_value *v);
#define CAPDAGFORMAL_WF_ASK_SAME 3
/* CapDAG.Exec.WfAsk.same; takes ownership of the fields. */
lungo_value *capdagFormal_wf_ask_same(lungo_value *u);
/* Field u of CapDAG.Exec.WfAsk.same (borrowed). */
const lungo_value *capdagFormal_wf_ask_same_u(const lungo_value *v);

/* CapDAG.Bifaci.Credit.Gate.acquire : CapDAG.Bifaci.Credit.Gate → Nat → CapDAG.Bifaci.Credit.Acquire */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_acquire(const lungo_value *g, const lungo_value *n, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Credit.Gate.close : CapDAG.Bifaci.Credit.Gate → String → CapDAG.Bifaci.Credit.Gate */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_close(const lungo_value *g, const lungo_value *reason, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Credit.Gate.grant : CapDAG.Bifaci.Credit.Gate → Nat → CapDAG.Bifaci.Credit.Gate */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_grant(const lungo_value *g, const lungo_value *n, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Credit.Gate.opened : Nat → CapDAG.Bifaci.Credit.Gate */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_gate_opened(const lungo_value *window, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Credit.Window.arrive : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Arrival */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_window_arrive(const lungo_value *w, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Credit.Window.consume : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_consume(const lungo_value *w, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Credit.Window.continued : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_continued(const lungo_value *w, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Credit.Window.flush : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_flush(const lungo_value *w, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Credit.Window.opened : Nat → CapDAG.Bifaci.Credit.Window */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_window_opened(const lungo_value *window, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Credit.grantTarget : List (Option String) → Option String → Option (Option String) */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_grant_target(const lungo_value *streams, const lungo_value *named, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Credit.negotiate : Nat → Nat → Option Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_negotiate(const lungo_value *ours, const lungo_value *theirs, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Flow.FrameType.code : CapDAG.Bifaci.Flow.FrameType → Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_code(const lungo_value *a, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Flow.FrameType.isFlow : CapDAG.Bifaci.Flow.FrameType → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_is_flow(const lungo_value *a, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Flow.FrameType.isTerminal : CapDAG.Bifaci.Flow.FrameType → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_is_terminal(const lungo_value *a, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Flow.FrameType.ofCode : Nat → Option CapDAG.Bifaci.Flow.FrameType */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_of_code(const lungo_value *a, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Flow.Reorder.accept : CapDAG.Bifaci.Flow.Reorder → Nat → Nat → CapDAG.Bifaci.Flow.Accepted */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_accept(const lungo_value *r, const lungo_value *seq, const lungo_value *limit, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Flow.Reorder.start : CapDAG.Bifaci.Flow.Reorder */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_start(lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.admit : CapDAG.Bifaci.Pools.State → Nat → Option CapDAG.Bifaci.Pools.State */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_admit(const lungo_value *s, const lungo_value *ticket, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.admitNext : CapDAG.Bifaci.Pools.State → Option (CapDAG.Bifaci.Pools.Waiter × CapDAG.Bifaci.Pools.State) */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_admit_next(const lungo_value *s, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.arrive : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.Arrival */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_state_arrive(const lungo_value *s, const lungo_value *chain, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.empty : CapDAG.Bifaci.Pools.State */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_empty(lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.hasRoom : CapDAG.Bifaci.Pools.State → List String → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_has_room(const lungo_value *s, const lungo_value *chain, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.heldBack : CapDAG.Bifaci.Pools.State → String → Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_held_back(const lungo_value *s, const lungo_value *name, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.join : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.Arrival */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_join(const lungo_value *s, const lungo_value *chain, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.leave : CapDAG.Bifaci.Pools.State → Nat → CapDAG.Bifaci.Pools.State */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_leave(const lungo_value *s, const lungo_value *ticket, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.position : CapDAG.Bifaci.Pools.State → Nat → Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_position(const lungo_value *s, const lungo_value *ticket, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.release : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.State */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_release(const lungo_value *s, const lungo_value *chain, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.State.setCapacity : CapDAG.Bifaci.Pools.State → String → Nat → CapDAG.Bifaci.Pools.State */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_set_capacity(const lungo_value *s, const lungo_value *name, const lungo_value *capacity, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.advertised : Bool → String → Nat → Option Nat → Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_advertised(const lungo_value *running, const lungo_value *pool, const lungo_value *configured, const lungo_value *available, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.chain : String → List (String × List String) → List String */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_chain(const lungo_value *cap, const lungo_value *shared, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.effective : Nat → Option Nat → Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_effective(const lungo_value *configured, const lungo_value *available, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Pools.patience : Option Nat → Nat → CapDAG.Bifaci.Pools.Patience */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_patience(const lungo_value *unavailable_for, const lungo_value *grace, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Request.Phase.after : CapDAG.Bifaci.Request.Phase → CapDAG.Bifaci.Flow.FrameType → CapDAG.Bifaci.Request.Phase */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_after(const lungo_value *p, const lungo_value *frame, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Request.check : List CapDAG.Bifaci.Request.Emitted → Option CapDAG.Bifaci.Request.Violation */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_check(const lungo_value *frames, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Request.dispose : Bool → Bool → CapDAG.Bifaci.Request.Disposition */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_dispose(const lungo_value *live, const lungo_value *ended_lately, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Request.ledger : Int → CapDAG.Bifaci.Flow.FrameType → Nat → Int */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_ledger(const lungo_value *remaining, const lungo_value *frame, const lungo_value *granted, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Request.terminalOf : CapDAG.Bifaci.Flow.FrameType → Option CapDAG.Bifaci.Request.Terminal */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_terminal_of(const lungo_value *a, lungo_value **result, lungo_error **error);

/* CapDAG.Bifaci.Request.write : Bool → CapDAG.Bifaci.Flow.FrameType → CapDAG.Bifaci.Request.Write */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_write(const lungo_value *over, const lungo_value *frame, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_accepts(const lungo_value *pattern, const lungo_value *cap, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_comparable(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_dispatch(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_effect_ok(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_equivalent(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.flows : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_flows(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.mayDispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_may_dispatch(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.mayFlow : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_may_flow(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryAdmits : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_admits(const lungo_value *q, const lungo_value *c, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryBetween : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_between(const lungo_value *input, const lungo_value *output, const lungo_value *tags, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryConsuming : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_consuming(const lungo_value *input, const lungo_value *tags, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryGrade : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → CapDAG.Grade */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_grade(const lungo_value *q, const lungo_value *c, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryMayAdmit : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_may_admit(const lungo_value *q, const lungo_value *c, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryOfPattern : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_of_pattern(const lungo_value *p, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryOfRequest : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_of_request(const lungo_value *r, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryProducing : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_producing(const lungo_value *output, const lungo_value *tags, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_ranking_key(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_select(const lungo_value *candidates, const lungo_value *request, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_specificity(const lungo_value *c, lungo_value **result, lungo_error **error);

/* TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_make(const lungo_value *scheme, const lungo_value *tags, lungo_value **result, lungo_error **error);

#ifdef __cplusplus
}
#endif

#endif /* CAPDAGFORMAL_H */
