/* Generated by lungo 1.81.24 from Lean 4.34.1 for program capdagFormal. Do not edit. */
#ifndef CAPDAGFORMAL_H
#define CAPDAGFORMAL_H

#include "lungo.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initializes the program; every function initializes it on first use. */
void capdagFormal_initialize(void);

/* CapDAG.Exec.WfCap */
#define CAPDAGFORMAL_WF_CAP_FINGERPRINT "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830"
lungo_type *capdagFormal_wf_cap_type(void);
#define CAPDAGFORMAL_WF_CAP_MK 0
/* CapDAG.Exec.WfCap.mk; takes ownership of the fields. */
lungo_value *capdagFormal_wf_cap_mk(lungo_value *input, lungo_value *output, lungo_value *other, lungo_value *effect);
/* Field input of CapDAG.Exec.WfCap.mk (borrowed). */
const lungo_value *capdagFormal_wf_cap_input(const lungo_value *v);
/* Field output of CapDAG.Exec.WfCap.mk (borrowed). */
const lungo_value *capdagFormal_wf_cap_output(const lungo_value *v);
/* Field other of CapDAG.Exec.WfCap.mk (borrowed). */
const lungo_value *capdagFormal_wf_cap_other(const lungo_value *v);
/* Field effect of CapDAG.Exec.WfCap.mk (borrowed). */
const lungo_value *capdagFormal_wf_cap_effect(const lungo_value *v);

/* CapDAG.Effect */
#define CAPDAGFORMAL_EFFECT_FINGERPRINT "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477"
lungo_type *capdagFormal_effect_type(void);
#define CAPDAGFORMAL_EFFECT_UNSPECIFIED 0
/* CapDAG.Effect.unspecified; takes ownership of the fields. */
lungo_value *capdagFormal_effect_unspecified(void);
#define CAPDAGFORMAL_EFFECT_DECLARED 1
/* CapDAG.Effect.declared; takes ownership of the fields. */
lungo_value *capdagFormal_effect_declared(void);
#define CAPDAGFORMAL_EFFECT_NONE 2
/* CapDAG.Effect.none; takes ownership of the fields. */
lungo_value *capdagFormal_effect_none(void);
#define CAPDAGFORMAL_EFFECT_PATCH 3
/* CapDAG.Effect.patch; takes ownership of the fields. */
lungo_value *capdagFormal_effect_patch(void);

/* CapDAG.Exec.WfQuery */
#define CAPDAGFORMAL_WF_QUERY_FINGERPRINT "e734861d70e3177f6563c4492990bb65131f0450b8dfc62071eb61b6c5f08b8e"
lungo_type *capdagFormal_wf_query_type(void);
#define CAPDAGFORMAL_WF_QUERY_MK 0
/* CapDAG.Exec.WfQuery.mk; takes ownership of the fields. */
lungo_value *capdagFormal_wf_query_mk(lungo_value *input, lungo_value *output, lungo_value *tags, lungo_value *effect);
/* Field input of CapDAG.Exec.WfQuery.mk (borrowed). */
const lungo_value *capdagFormal_wf_query_input(const lungo_value *v);
/* Field output of CapDAG.Exec.WfQuery.mk (borrowed). */
const lungo_value *capdagFormal_wf_query_output(const lungo_value *v);
/* Field tags of CapDAG.Exec.WfQuery.mk (borrowed). */
const lungo_value *capdagFormal_wf_query_tags(const lungo_value *v);
/* Field effect of CapDAG.Exec.WfQuery.mk (borrowed). */
const lungo_value *capdagFormal_wf_query_effect(const lungo_value *v);

/* TaggedUrn.Exec.Wf */
#define CAPDAGFORMAL_WF_FINGERPRINT "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785"
lungo_type *capdagFormal_wf_type(void);

/* CapDAG.Grade */
#define CAPDAGFORMAL_GRADE_FINGERPRINT "0a2a20a14d9ecca6121343df2d8a7f2478b3e837710ed522ed385d35efdf46f2"
lungo_type *capdagFormal_grade_type(void);
#define CAPDAGFORMAL_GRADE_EXACT 0
/* CapDAG.Grade.exact; takes ownership of the fields. */
lungo_value *capdagFormal_grade_exact(void);
#define CAPDAGFORMAL_GRADE_GUARANTEED 1
/* CapDAG.Grade.guaranteed; takes ownership of the fields. */
lungo_value *capdagFormal_grade_guaranteed(void);
#define CAPDAGFORMAL_GRADE_POSSIBLE 2
/* CapDAG.Grade.possible; takes ownership of the fields. */
lungo_value *capdagFormal_grade_possible(void);
#define CAPDAGFORMAL_GRADE_NONE 3
/* CapDAG.Grade.none; takes ownership of the fields. */
lungo_value *capdagFormal_grade_none(void);

/* TaggedUrn.Constraint */
#define CAPDAGFORMAL_CONSTRAINT_FINGERPRINT "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"
lungo_type *capdagFormal_constraint_type(void);
#define CAPDAGFORMAL_CONSTRAINT_MISSING 0
/* TaggedUrn.Constraint.missing; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_missing(void);
#define CAPDAGFORMAL_CONSTRAINT_UNCONSTRAINED 1
/* TaggedUrn.Constraint.unconstrained; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_unconstrained(void);
#define CAPDAGFORMAL_CONSTRAINT_OPTIONAL_NOT 2
/* TaggedUrn.Constraint.optionalNot; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_optional_not(lungo_value *value);
/* Field value of TaggedUrn.Constraint.optionalNot (borrowed). */
const lungo_value *capdagFormal_constraint_optional_not_value(const lungo_value *v);
#define CAPDAGFORMAL_CONSTRAINT_PRESENT 3
/* TaggedUrn.Constraint.present; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_present(void);
#define CAPDAGFORMAL_CONSTRAINT_PRESENT_NOT 4
/* TaggedUrn.Constraint.presentNot; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_present_not(lungo_value *value);
/* Field value of TaggedUrn.Constraint.presentNot (borrowed). */
const lungo_value *capdagFormal_constraint_present_not_value(const lungo_value *v);
#define CAPDAGFORMAL_CONSTRAINT_EXACT 5
/* TaggedUrn.Constraint.exact; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_exact(lungo_value *value);
/* Field value of TaggedUrn.Constraint.exact (borrowed). */
const lungo_value *capdagFormal_constraint_exact_value(const lungo_value *v);
#define CAPDAGFORMAL_CONSTRAINT_ABSENT 6
/* TaggedUrn.Constraint.absent; takes ownership of the fields. */
lungo_value *capdagFormal_constraint_absent(void);

/* CapDAG.Exec.WfAsk */
#define CAPDAGFORMAL_WF_ASK_FINGERPRINT "d286477c7abc4e6bc6ee2d06889372b71a5bb06605b592ebabb6ad3eaf71b952"
lungo_type *capdagFormal_wf_ask_type(void);
#define CAPDAGFORMAL_WF_ASK_UNKNOWN 0
/* CapDAG.Exec.WfAsk.unknown; takes ownership of the fields. */
lungo_value *capdagFormal_wf_ask_unknown(void);
#define CAPDAGFORMAL_WF_ASK_WITHIN 1
/* CapDAG.Exec.WfAsk.within; takes ownership of the fields. */
lungo_value *capdagFormal_wf_ask_within(lungo_value *u);
/* Field u of CapDAG.Exec.WfAsk.within (borrowed). */
const lungo_value *capdagFormal_wf_ask_within_u(const lungo_value *v);
#define CAPDAGFORMAL_WF_ASK_COVERS 2
/* CapDAG.Exec.WfAsk.covers; takes ownership of the fields. */
lungo_value *capdagFormal_wf_ask_covers(lungo_value *u);
/* Field u of CapDAG.Exec.WfAsk.covers (borrowed). */
const lungo_value *capdagFormal_wf_ask_covers_u(const lungo_value *v);
#define CAPDAGFORMAL_WF_ASK_SAME 3
/* CapDAG.Exec.WfAsk.same; takes ownership of the fields. */
lungo_value *capdagFormal_wf_ask_same(lungo_value *u);
/* Field u of CapDAG.Exec.WfAsk.same (borrowed). */
const lungo_value *capdagFormal_wf_ask_same_u(const lungo_value *v);

/* CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_accepts(const lungo_value *pattern, const lungo_value *cap, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_comparable(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_dispatch(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_effect_ok(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_equivalent(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.flows : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_flows(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.mayDispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_may_dispatch(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.mayFlow : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_may_flow(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryAdmits : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_admits(const lungo_value *q, const lungo_value *c, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryBetween : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_between(const lungo_value *input, const lungo_value *output, const lungo_value *tags, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryConsuming : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_consuming(const lungo_value *input, const lungo_value *tags, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryGrade : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → CapDAG.Grade */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_grade(const lungo_value *q, const lungo_value *c, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryMayAdmit : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_may_admit(const lungo_value *q, const lungo_value *c, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryOfPattern : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_of_pattern(const lungo_value *p, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryOfRequest : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_of_request(const lungo_value *r, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.queryProducing : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_query_producing(const lungo_value *output, const lungo_value *tags, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_ranking_key(const lungo_value *candidate, const lungo_value *request, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_select(const lungo_value *candidates, const lungo_value *request, lungo_value **result, lungo_error **error);

/* CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_specificity(const lungo_value *c, lungo_value **result, lungo_error **error);

/* TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t capdagFormal_make(const lungo_value *scheme, const lungo_value *tags, lungo_value **result, lungo_error **error);

#ifdef __cplusplus
}
#endif

#endif /* CAPDAGFORMAL_H */
